<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('grade_books', function (Blueprint $table) {
            $table->id();
            $table->string('tenant_id')->index();
            $table->unsignedBigInteger('student_id');
            $table->unsignedBigInteger('class_id');
            $table->unsignedBigInteger('section_id')->nullable();
            $table->string('academic_year');
            $table->string('term')->nullable(); // Term 1, Term 2, Annual, etc.
            
            // Overall performance
            $table->decimal('total_marks', 10, 2)->default(0);
            $table->decimal('max_total_marks', 10, 2)->default(0);
            $table->decimal('percentage', 5, 2)->default(0);
            $table->string('overall_grade', 10)->nullable(); // Letter grade
            $table->decimal('overall_gpa', 3, 2)->nullable(); // Overall GPA
            
            // Statistics
            $table->integer('rank')->nullable(); // Class rank
            $table->integer('total_subjects')->default(0);
            $table->integer('passed_subjects')->default(0);
            $table->integer('failed_subjects')->default(0);
            
            // Status
            $table->enum('status', ['pass', 'fail', 'pending'])->default('pending');
            $table->boolean('is_published')->default(false);
            $table->date('published_at')->nullable();
            
            // Generated by
            $table->unsignedBigInteger('generated_by')->nullable();
            $table->timestamp('generated_at')->nullable();
            
            $table->timestamps();

            $table->foreign('tenant_id')->references('id')->on('tenants')->onDelete('cascade');
            $table->foreign('student_id')->references('id')->on('students')->onDelete('cascade');
            $table->foreign('class_id')->references('id')->on('classes')->onDelete('cascade');
            $table->foreign('section_id')->references('id')->on('sections')->onDelete('set null');
            $table->foreign('generated_by')->references('id')->on('users')->onDelete('set null');
            
            $table->unique(['tenant_id', 'student_id', 'academic_year', 'term'], 'unique_student_term');
            $table->index(['tenant_id', 'class_id', 'section_id']);
            $table->index(['tenant_id', 'academic_year', 'term']);
            $table->index(['status']);
            $table->index(['is_published']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('grade_books');
    }
};
