<?php

return [
    'languages' => [
        'en' => 'English',
        'hi' => 'Hindi',
        'kn' => 'Kannada',
    ],
    'default_language' => 'en',

    'pages' => [
        'home' => [
            'en' => [
                'hero_badge' => 'Excellence in Education Since 2000',
                'hero_heading' => 'Welcome to {tenant_name}',
                'hero_description' => '{tenant_description} - Empowering students to achieve their full potential through innovative learning and character development.',
                'hero_button_text' => 'Apply for Admission',
                'hero_button_url' => '/admission',
                'stats_students' => '{tenant_student_count}',
                'stats_teachers' => '50+',
                'stats_programs' => '20+',
                'stats_years' => '25+',
                'features_title' => 'Why Choose {tenant_name}?',
                'features_description' => 'Discover what makes us the preferred choice for quality education and holistic development',
                'programs_title' => 'Our Programs',
                'programs_description' => 'Comprehensive educational programs designed to nurture your child\'s potential',
                'testimonials_title' => 'What Parents Say',
                'testimonials_description' => 'Hear from our community about their experience with our school',
            ],
            'hi' => [
                'hero_badge' => '2000 से शिक्षा में उत्कृष्टता',
                'hero_heading' => '{tenant_name} में आपका स्वागत है',
                'hero_description' => '{tenant_description} - नवाचारी शिक्षा और चरित्र विकास के माध्यम से छात्रों को उनकी पूरी क्षमता हासिल करने के लिए सशक्त बनाना।',
                'hero_button_text' => 'प्रवेश के लिए आवेदन करें',
                'hero_button_url' => '/admission',
                'stats_students' => '{tenant_student_count}',
                'stats_teachers' => '50+',
                'stats_programs' => '20+',
                'stats_years' => '25+',
                'features_title' => '{tenant_name} क्यों चुनें?',
                'features_description' => 'जानें कि गुणवत्तापूर्ण शिक्षा और समग्र विकास के लिए हमें पसंदीदा विकल्प क्या बनाता है',
                'programs_title' => 'हमारे कार्यक्रम',
                'programs_description' => 'आपके बच्चे की क्षमता को विकसित करने के लिए डिज़ाइन किए गए व्यापक शैक्षिक कार्यक्रम',
                'testimonials_title' => 'माता-पिता क्या कहते हैं',
                'testimonials_description' => 'हमारे स्कूल के साथ अपने अनुभव के बारे में हमारे समुदाय से सुनें',
            ],
            'kn' => [
                'hero_badge' => '2000 ರಿಂದ ಶಿಕ್ಷಣದಲ್ಲಿ ಶ್ರೇಷ್ಠತೆ',
                'hero_heading' => '{tenant_name} ಗೆ ಸ್ವಾಗತ',
                'hero_description' => '{tenant_description} - ನಾವೀನ್ಯತೆಯ ಕಲಿಕೆ ಮತ್ತು ಚಾರಿತ್ರಿಕ ಅಭಿವೃದ್ಧಿಯ ಮೂಲಕ ವಿದ್ಯಾರ್ಥಿಗಳು ತಮ್ಮ ಪೂರ್ಣ ಸಾಮರ್ಥ್ಯವನ್ನು ಸಾಧಿಸಲು ಸಶಕ್ತಗೊಳಿಸುವುದು।',
                'hero_button_text' => 'ಪ್ರವೇಶಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
                'hero_button_url' => '/admission',
                'stats_students' => '{tenant_student_count}',
                'stats_teachers' => '50+',
                'stats_programs' => '20+',
                'stats_years' => '25+',
                'features_title' => '{tenant_name} ಅನ್ನು ಏಕೆ ಆರಿಸಬೇಕು?',
                'features_description' => 'ಗುಣಮಟ್ಟದ ಶಿಕ್ಷಣ ಮತ್ತು ಸಮಗ್ರ ಅಭಿವೃದ್ಧಿಗಾಗಿ ನಮ್ಮನ್ನು ಆದ್ಯತೆಯ ಆಯ್ಕೆಯನ್ನಾಗಿ ಮಾಡುವುದು ಏನು ಎಂಬುದನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ',
                'programs_title' => 'ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳು',
                'programs_description' => 'ನಿಮ್ಮ ಮಗುವಿನ ಸಾಮರ್ಥ್ಯವನ್ನು ಬೆಳೆಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಸಮಗ್ರ ಶೈಕ್ಷಣಿಕ ಕಾರ್ಯಕ್ರಮಗಳು',
                'testimonials_title' => 'ಪೋಷಕರು ಏನು ಹೇಳುತ್ತಾರೆ',
                'testimonials_description' => 'ನಮ್ಮ ಶಾಲೆಯೊಂದಿಗಿನ ಅವರ ಅನುಭವದ ಬಗ್ಗೆ ನಮ್ಮ ಸಮುದಾಯದಿಂದ ಕೇಳಿ',
            ],
        ],
        'about' => [
            'en' => [
                'hero_heading' => 'About Our School',
                'hero_description' => 'Learn about our mission, values, and commitment to student success.',
                'story_title' => 'Building Excellence Since Day One',
                'story_content' => 'Founded with a vision to provide exceptional education, Our School has been at the forefront of academic excellence for over two decades.',
                'stat1_value' => '1000+',
                'stat1_label' => 'Happy Students',
                'stat2_value' => '50+',
                'stat2_label' => 'Expert Teachers',
                'info_title' => 'Why Choose Us',
                'info_item1_label' => 'Accredited Institution',
                'info_item1_value' => 'Recognized by Education Board',
                'info_item2_label' => 'Modern Facilities',
                'info_item2_value' => 'State-of-the-art Infrastructure',
                'info_item3_label' => 'Experienced Faculty',
                'info_item3_value' => 'Qualified & Dedicated Teachers',
                'info_item4_label' => 'Holistic Development',
                'info_item4_value' => 'Academic & Character Building',
                'mission_title' => 'Our Mission & Values',
                'mission_description' => 'Guiding principles that shape our educational approach and define who we are',
                'value1_title' => 'Innovation',
                'value1_description' => 'Embracing new technologies and teaching methodologies to enhance learning outcomes and prepare students for the future.',
                'value2_title' => 'Community',
                'value2_description' => 'Building strong partnerships between students, parents, teachers, and the community to create a supportive learning environment.',
                'value3_title' => 'Excellence',
                'value3_description' => 'Striving for the highest standards in academics, character, and personal development to ensure student success.',
                'vision_title' => 'Shaping Tomorrow\'s Leaders',
                'vision_content' => 'To be recognized as a premier educational institution that empowers students to become confident, compassionate, and capable leaders.',
                'principles_title' => 'Our Core Principles',
                'principle1_title' => 'Holistic Development',
                'principle1_description' => 'Nurturing academic, social, emotional, and physical growth in every student.',
                'principle2_title' => 'Individualized Learning',
                'principle2_description' => 'Recognizing and supporting each student\'s unique learning style and pace.',
                'principle3_title' => 'Character Building',
                'principle3_description' => 'Instilling integrity, respect, responsibility, and ethical values.',
            ],
            'hi' => [
                'hero_heading' => 'हमारे स्कूल के बारे में',
                'hero_description' => 'हमारे मिशन, मूल्यों और छात्र सफलता के प्रति प्रतिबद्धता के बारे में जानें।',
                'story_title' => 'पहले दिन से उत्कृष्टता का निर्माण',
                'story_content' => 'असाधारण शिक्षा प्रदान करने के दृष्टिकोण के साथ स्थापित, हमारा स्कूल दो दशकों से अधिक समय से शैक्षणिक उत्कृष्टता के अग्रिम पंक्ति में रहा है।',
                'stat1_value' => '1000+',
                'stat1_label' => 'खुश छात्र',
                'stat2_value' => '50+',
                'stat2_label' => 'विशेषज्ञ शिक्षक',
                'info_title' => 'हमें क्यों चुनें',
                'info_item1_label' => 'मान्यता प्राप्त संस्थान',
                'info_item1_value' => 'शिक्षा बोर्ड द्वारा मान्यता प्राप्त',
                'info_item2_label' => 'आधुनिक सुविधाएं',
                'info_item2_value' => 'अत्याधुनिक बुनियादी ढांचा',
                'info_item3_label' => 'अनुभवी संकाय',
                'info_item3_value' => 'योग्य और समर्पित शिक्षक',
                'info_item4_label' => 'समग्र विकास',
                'info_item4_value' => 'शैक्षणिक और चरित्र निर्माण',
                'mission_title' => 'हमारा मिशन और मूल्य',
                'mission_description' => 'मार्गदर्शक सिद्धांत जो हमारे शैक्षिक दृष्टिकोण को आकार देते हैं और परिभाषित करते हैं कि हम कौन हैं',
                'value1_title' => 'नवाचार',
                'value1_description' => 'सीखने के परिणामों को बढ़ाने और छात्रों को भविष्य के लिए तैयार करने के लिए नई प्रौद्योगिकियों और शिक्षण पद्धतियों को अपनाना।',
                'value2_title' => 'समुदाय',
                'value2_description' => 'एक सहायक सीखने के वातावरण बनाने के लिए छात्रों, माता-पिता, शिक्षकों और समुदाय के बीच मजबूत साझेदारी बनाना।',
                'value3_title' => 'उत्कृष्टता',
                'value3_description' => 'छात्र सफलता सुनिश्चित करने के लिए शैक्षणिक, चरित्र और व्यक्तिगत विकास में उच्चतम मानकों के लिए प्रयास करना।',
                'vision_title' => 'कल के नेताओं को आकार देना',
                'vision_content' => 'एक प्रमुख शैक्षिक संस्थान के रूप में मान्यता प्राप्त करना जो छात्रों को आत्मविश्वासी, करुणामय और सक्षम नेता बनने के लिए सशक्त बनाता है।',
                'principles_title' => 'हमारे मूल सिद्धांत',
                'principle1_title' => 'समग्र विकास',
                'principle1_description' => 'प्रत्येक छात्र में शैक्षणिक, सामाजिक, भावनात्मक और शारीरिक विकास को बढ़ावा देना।',
                'principle2_title' => 'व्यक्तिगत शिक्षा',
                'principle2_description' => 'प्रत्येक छात्र की अद्वितीय सीखने की शैली और गति को पहचानना और समर्थन करना।',
                'principle3_title' => 'चरित्र निर्माण',
                'principle3_description' => 'ईमानदारी, सम्मान, जिम्मेदारी और नैतिक मूल्यों को स्थापित करना।',
            ],
            'kn' => [
                'hero_heading' => 'ನಮ್ಮ ಶಾಲೆಯ ಬಗ್ಗೆ',
                'hero_description' => 'ನಮ್ಮ ಧ್ಯೇಯ, ಮೌಲ್ಯಗಳು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿ ಯಶಸ್ಸಿಗೆ ನಮ್ಮ ಬದ್ಧತೆಯ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ।',
                'story_title' => 'ಮೊದಲ ದಿನದಿಂದ ಶ್ರೇಷ್ಠತೆಯನ್ನು ನಿರ್ಮಿಸುವುದು',
                'story_content' => 'ವಿಶೇಷ ಶಿಕ್ಷಣವನ್ನು ಒದಗಿಸುವ ದೃಷ್ಟಿಕೋನದೊಂದಿಗೆ ಸ್ಥಾಪಿಸಲಾಗಿದೆ, ನಮ್ಮ ಶಾಲೆಯು ಎರಡು ದಶಕಗಳಿಗಿಂತ ಹೆಚ್ಚು ಕಾಲ ಶೈಕ್ಷಣಿಕ ಶ್ರೇಷ್ಠತೆಯ ಮುಂಚೂಣಿಯಲ್ಲಿದೆ।',
                'stat1_value' => '1000+',
                'stat1_label' => 'ಸಂತೋಷದ ವಿದ್ಯಾರ್ಥಿಗಳು',
                'stat2_value' => '50+',
                'stat2_label' => 'ತಜ್ಞ ಶಿಕ್ಷಕರು',
                'info_title' => 'ನಮ್ಮನ್ನು ಏಕೆ ಆರಿಸಬೇಕು',
                'info_item1_label' => 'ಮಾನ್ಯತೆ ಪಡೆದ ಸಂಸ್ಥೆ',
                'info_item1_value' => 'ಶಿಕ್ಷಣ ಮಂಡಳಿಯಿಂದ ಮಾನ್ಯತೆ',
                'info_item2_label' => 'ಆಧುನಿಕ ಸೌಲಭ್ಯಗಳು',
                'info_item2_value' => 'ಅತ್ಯಾಧುನಿಕ ಮೂಲಸೌಕರ್ಯ',
                'info_item3_label' => 'ಅನುಭವಿ ಸಿಬ್ಬಂದಿ',
                'info_item3_value' => 'ಯೋಗ್ಯ ಮತ್ತು ಸಮರ್ಪಿತ ಶಿಕ್ಷಕರು',
                'info_item4_label' => 'ಸಮಗ್ರ ಅಭಿವೃದ್ಧಿ',
                'info_item4_value' => 'ಶೈಕ್ಷಣಿಕ ಮತ್ತು ಚಾರಿತ್ರಿಕ ನಿರ್ಮಾಣ',
                'mission_title' => 'ನಮ್ಮ ಧ್ಯೇಯ ಮತ್ತು ಮೌಲ್ಯಗಳು',
                'mission_description' => 'ನಮ್ಮ ಶೈಕ್ಷಣಿಕ ವಿಧಾನವನ್ನು ರೂಪಿಸುವ ಮತ್ತು ನಾವು ಯಾರು ಎಂಬುದನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುವ ಮಾರ್ಗದರ್ಶಿ ತತ್ವಗಳು',
                'value1_title' => 'ನಾವೀನ್ಯತೆ',
                'value1_description' => 'ಕಲಿಕೆಯ ಫಲಿತಾಂಶಗಳನ್ನು ಹೆಚ್ಚಿಸಲು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಭವಿಷ್ಯಕ್ಕಾಗಿ ಸಿದ್ಧಪಡಿಸಲು ಹೊಸ ತಂತ್ರಜ್ಞಾನಗಳು ಮತ್ತು ಕಲಿಕೆ ವಿಧಾನಗಳನ್ನು ಅಳವಡಿಸಿಕೊಳ್ಳುವುದು।',
                'value2_title' => 'ಸಮುದಾಯ',
                'value2_description' => 'ಸಹಾಯಕ ಕಲಿಕೆಯ ವಾತಾವರಣವನ್ನು ರಚಿಸಲು ವಿದ್ಯಾರ್ಥಿಗಳು, ಪೋಷಕರು, ಶಿಕ್ಷಕರು ಮತ್ತು ಸಮುದಾಯದ ನಡುವೆ ಬಲವಾದ ಪಾಲುದಾರಿಕೆಗಳನ್ನು ನಿರ್ಮಿಸುವುದು।',
                'value3_title' => 'ಶ್ರೇಷ್ಠತೆ',
                'value3_description' => 'ವಿದ್ಯಾರ್ಥಿ ಯಶಸ್ಸನ್ನು ಖಚಿತಪಡಿಸಲು ಶೈಕ್ಷಣಿಕ, ಚಾರಿತ್ರಿಕ ಮತ್ತು ವೈಯಕ್ತಿಕ ಅಭಿವೃದ್ಧಿಯಲ್ಲಿ ಅತ್ಯುನ್ನತ ಮಾನದಂಡಗಳಿಗಾಗಿ ಶ್ರಮಿಸುವುದು।',
                'vision_title' => 'ನಾಳೆಯ ನೇತೃತ್ವವನ್ನು ರೂಪಿಸುವುದು',
                'vision_content' => 'ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಆತ್ಮವಿಶ್ವಾಸ, ಸಹಾನುಭೂತಿ ಮತ್ತು ಸಮರ್ಥ ನೇತೃತ್ವವಾಗಿ ಪರಿವರ್ತಿಸುವ ಪ್ರಮುಖ ಶೈಕ್ಷಣಿಕ ಸಂಸ್ಥೆಯಾಗಿ ಗುರುತಿಸಲ್ಪಡುವುದು।',
                'principles_title' => 'ನಮ್ಮ ಮೂಲ ತತ್ವಗಳು',
                'principle1_title' => 'ಸಮಗ್ರ ಅಭಿವೃದ್ಧಿ',
                'principle1_description' => 'ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಯಲ್ಲಿ ಶೈಕ್ಷಣಿಕ, ಸಾಮಾಜಿಕ, ಭಾವನಾತ್ಮಕ ಮತ್ತು ಶಾರೀರಿಕ ಬೆಳವಣಿಗೆಯನ್ನು ಪೋಷಿಸುವುದು।',
                'principle2_title' => 'ವೈಯಕ್ತಿಕ ಕಲಿಕೆ',
                'principle2_description' => 'ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಯ ಅನನ್ಯ ಕಲಿಕೆಯ ಶೈಲಿ ಮತ್ತು ವೇಗವನ್ನು ಗುರುತಿಸುವುದು ಮತ್ತು ಬೆಂಬಲಿಸುವುದು।',
                'principle3_title' => 'ಚಾರಿತ್ರಿಕ ನಿರ್ಮಾಣ',
                'principle3_description' => 'ಸಮಗ್ರತೆ, ಗೌರವ, ಜವಾಬ್ದಾರಿ ಮತ್ತು ನೈತಿಕ ಮೌಲ್ಯಗಳನ್ನು ಸ್ಥಾಪಿಸುವುದು।',
            ],
        ],
        'programs' => [
            'en' => [
                'hero_heading' => 'Our Programs',
                'hero_description' => 'Discover comprehensive educational programs designed to nurture your child\'s potential and prepare them for a successful future.',
                'programs_title' => 'Academic Programs',
                'programs_description' => 'Comprehensive curriculum designed to meet diverse learning needs',
                'highlights_title' => 'Program Highlights',
                'highlights_description' => 'What makes our programs stand out',
                'highlight1_title' => 'Expert Faculty',
                'highlight1_description' => 'Highly qualified and experienced teachers dedicated to student success.',
                'highlight2_title' => 'Modern Facilities',
                'highlight2_description' => 'State-of-the-art classrooms, labs, and learning spaces.',
                'highlight3_title' => 'Flexible Scheduling',
                'highlight3_description' => 'Programs designed to accommodate diverse learning needs.',
                'highlight4_title' => 'Certified Programs',
                'highlight4_description' => 'Accredited curriculum meeting national education standards.',
                'cta_title' => 'Ready to Get Started?',
                'cta_description' => 'Join our community and give your child the best educational experience',
                'cta_button_text' => 'Apply for Admission',
            ],
            'hi' => [
                'hero_heading' => 'हमारे कार्यक्रम',
                'hero_description' => 'अपने बच्चे की क्षमता को विकसित करने और उन्हें सफल भविष्य के लिए तैयार करने के लिए डिज़ाइन किए गए व्यापक शैक्षिक कार्यक्रमों की खोज करें।',
                'programs_title' => 'शैक्षणिक कार्यक्रम',
                'programs_description' => 'विविध शिक्षण आवश्यकताओं को पूरा करने के लिए डिज़ाइन किया गया व्यापक पाठ्यक्रम',
                'highlights_title' => 'कार्यक्रम की मुख्य विशेषताएं',
                'highlights_description' => 'हमारे कार्यक्रमों को विशिष्ट बनाने वाली बातें',
                'highlight1_title' => 'विशेषज्ञ संकाय',
                'highlight1_description' => 'छात्र सफलता के लिए समर्पित अत्यधिक योग्य और अनुभवी शिक्षक।',
                'highlight2_title' => 'आधुनिक सुविधाएं',
                'highlight2_description' => 'अत्याधुनिक कक्षाएं, प्रयोगशालाएं और सीखने के स्थान।',
                'highlight3_title' => 'लचीला समय सारिणी',
                'highlight3_description' => 'विविध सीखने की आवश्यकताओं को समायोजित करने के लिए डिज़ाइन किए गए कार्यक्रम।',
                'highlight4_title' => 'प्रमाणित कार्यक्रम',
                'highlight4_description' => 'राष्ट्रीय शिक्षा मानकों को पूरा करने वाला मान्यता प्राप्त पाठ्यक्रम।',
                'cta_title' => 'शुरू करने के लिए तैयार हैं?',
                'cta_description' => 'हमारे समुदाय में शामिल हों और अपने बच्चे को सर्वोत्तम शैक्षिक अनुभव दें',
                'cta_button_text' => 'प्रवेश के लिए आवेदन करें',
            ],
            'kn' => [
                'hero_heading' => 'ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳು',
                'hero_description' => 'ನಿಮ್ಮ ಮಗುವಿನ ಸಾಮರ್ಥ್ಯವನ್ನು ಬೆಳೆಸಲು ಮತ್ತು ಯಶಸ್ವಿ ಭವಿಷ್ಯಕ್ಕಾಗಿ ಅವರನ್ನು ಸಿದ್ಧಪಡಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಸಮಗ್ರ ಶೈಕ್ಷಣಿಕ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ।',
                'programs_title' => 'ಶೈಕ್ಷಣಿಕ ಕಾರ್ಯಕ್ರಮಗಳು',
                'programs_description' => 'ವೈವಿಧ್ಯಮಯ ಕಲಿಕೆಯ ಅವಶ್ಯಕತೆಗಳನ್ನು ಪೂರೈಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಸಮಗ್ರ ಪಾಠ್ಯಕ್ರಮ',
                'highlights_title' => 'ಕಾರ್ಯಕ್ರಮದ ಮುಖ್ಯಾಂಶಗಳು',
                'highlights_description' => 'ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ವಿಶಿಷ್ಟವಾಗಿ ಮಾಡುವುದು',
                'highlight1_title' => 'ತಜ್ಞ ಸಿಬ್ಬಂದಿ',
                'highlight1_description' => 'ವಿದ್ಯಾರ್ಥಿ ಯಶಸ್ಸಿಗೆ ಸಮರ್ಪಿತರಾದ ಹೆಚ್ಚು ಅರ್ಹ ಮತ್ತು ಅನುಭವಿ ಶಿಕ್ಷಕರು।',
                'highlight2_title' => 'ಆಧುನಿಕ ಸೌಲಭ್ಯಗಳು',
                'highlight2_description' => 'ಅತ್ಯಾಧುನಿಕ ತರಗತಿಗಳು, ಪ್ರಯೋಗಾಲಯಗಳು ಮತ್ತು ಕಲಿಕೆಯ ಸ್ಥಳಗಳು।',
                'highlight3_title' => 'ನಮ್ಯ ವೇಳಾಪಟ್ಟಿ',
                'highlight3_description' => 'ವೈವಿಧ್ಯಮಯ ಕಲಿಕೆಯ ಅಗತ್ಯಗಳನ್ನು ಸಮನ್ವಯಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಕಾರ್ಯಕ್ರಮಗಳು।',
                'highlight4_title' => 'ಪ್ರಮಾಣೀಕೃತ ಕಾರ್ಯಕ್ರಮಗಳು',
                'highlight4_description' => 'ರಾಷ್ಟ್ರೀಯ ಶಿಕ್ಷಣ ಮಾನದಂಡಗಳನ್ನು ಪೂರೈಸುವ ಮಾನ್ಯತೆ ಪಡೆದ ಪಠ್ಯಕ್ರಮ।',
                'cta_title' => 'ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
                'cta_description' => 'ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ ಮತ್ತು ನಿಮ್ಮ ಮಗುವಿಗೆ ಉತ್ತಮ ಶೈಕ್ಷಣಿಕ ಅನುಭವವನ್ನು ನೀಡಿ',
                'cta_button_text' => 'ಪ್ರವೇಶಕ್ಕೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
            ],
        ],
        'facilities' => [
            'en' => [
                'hero_heading' => 'Our Facilities',
                'hero_description' => 'Explore our state-of-the-art facilities designed to enhance learning, creativity, and overall student development.',
                'facilities_title' => 'Campus Facilities',
                'facilities_description' => 'Modern infrastructure supporting excellence in education',
                'amenities_title' => 'Additional Amenities',
                'amenities_description' => 'Supporting facilities that enhance the learning experience',
                'cta_title' => 'Experience Our Facilities',
                'cta_description' => 'Schedule a campus tour to see our world-class facilities in person',
                'cta_button_text' => 'Schedule a Tour',
            ],
            'hi' => [
                'hero_heading' => 'हमारी सुविधाएं',
                'hero_description' => 'सीखने, रचनात्मकता और समग्र छात्र विकास को बढ़ाने के लिए डिज़ाइन की गई हमारी अत्याधुनिक सुविधाओं का अन्वेषण करें।',
                'facilities_title' => 'कैंपस सुविधाएं',
                'facilities_description' => 'शिक्षा में उत्कृष्टता का समर्थन करने वाला आधुनिक बुनियादी ढांचा',
                'amenities_title' => 'अतिरिक्त सुविधाएं',
                'amenities_description' => 'सहायक सुविधाएं जो सीखने के अनुभव को बढ़ाती हैं',
                'cta_title' => 'हमारी सुविधाओं का अनुभव करें',
                'cta_description' => 'हमारी विश्व स्तरीय सुविधाओं को व्यक्तिगत रूप से देखने के लिए कैंपस भ्रमण की योजना बनाएं',
                'cta_button_text' => 'भ्रमण की योजना बनाएं',
            ],
            'kn' => [
                'hero_heading' => 'ನಮ್ಮ ಸೌಲಭ್ಯಗಳು',
                'hero_description' => 'ಕಲಿಕೆ, ಸೃಜನಶೀಲತೆ ಮತ್ತು ಒಟ್ಟಾರೆ ವಿದ್ಯಾರ್ಥಿ ಅಭಿವೃದ್ಧಿಯನ್ನು ಹೆಚ್ಚಿಸಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ನಮ್ಮ ಅತ್ಯಾಧುನಿಕ ಸೌಲಭ್ಯಗಳನ್ನು ಅನ್ವೇಷಿಸಿ।',
                'facilities_title' => 'ಕ್ಯಾಂಪಸ್ ಸೌಲಭ್ಯಗಳು',
                'facilities_description' => 'ಶಿಕ್ಷಣದಲ್ಲಿ ಶ್ರೇಷ್ಠತೆಯನ್ನು ಬೆಂಬಲಿಸುವ ಆಧುನಿಕ ಮೂಲಸೌಕರ್ಯ',
                'amenities_title' => 'ಹೆಚ್ಚುವರಿ ಸೌಲಭ್ಯಗಳು',
                'amenities_description' => 'ಕಲಿಕೆಯ ಅನುಭವವನ್ನು ಹೆಚ್ಚಿಸುವ ಬೆಂಬಲ ಸೌಲಭ್ಯಗಳು',
                'cta_title' => 'ನಮ್ಮ ಸೌಲಭ್ಯಗಳನ್ನು ಅನುಭವಿಸಿ',
                'cta_description' => 'ನಮ್ಮ ವಿಶ್ವಮಟ್ಟದ ಸೌಲಭ್ಯಗಳನ್ನು ವೈಯಕ್ತಿಕವಾಗಿ ನೋಡಲು ಕ್ಯಾಂಪಸ್ ಪ್ರವಾಸವನ್ನು ನಿಗದಿಪಡಿಸಿ',
                'cta_button_text' => 'ಪ್ರವಾಸವನ್ನು ನಿಗದಿಪಡಿಸಿ',
            ],
        ],
        'admission' => [
            'en' => [
                'hero_badge' => 'Join Our Community',
                'hero_heading' => 'Admission Information',
                'hero_description' => 'Learn about our admission process and requirements for joining our school community.',
                'process_badge' => 'How to Apply',
                'process_title' => 'Admission Process',
                'process_description' => 'Simple steps to join our school community',
                'requirements_badge' => 'What You Need',
                'requirements_title' => 'Admission Requirements',
                'requirements_description' => 'Documents and information needed for admission',
                'dates_badge' => 'Timeline',
                'dates_title' => 'Important Dates',
                'dates_description' => 'Key dates for the admission process',
                'faq_badge' => 'Got Questions?',
                'faq_title' => 'Frequently Asked Questions',
                'faq_description' => 'Common questions about our admission process',
                'cta_title' => 'Ready to Begin Your Journey?',
                'cta_description' => 'Start your admission process today and join our vibrant learning community',
                'cta_button_text' => 'Contact Admission Office',
                'cta_button_text_2' => 'Learn More About Us',
            ],
            'hi' => [
                'hero_badge' => 'हमारे समुदाय में शामिल हों',
                'hero_heading' => 'प्रवेश जानकारी',
                'hero_description' => 'हमारे स्कूल समुदाय में शामिल होने के लिए हमारी प्रवेश प्रक्रिया और आवश्यकताओं के बारे में जानें।',
                'process_badge' => 'कैसे आवेदन करें',
                'process_title' => 'प्रवेश प्रक्रिया',
                'process_description' => 'हमारे स्कूल समुदाय में शामिल होने के सरल चरण',
                'requirements_badge' => 'आपको क्या चाहिए',
                'requirements_title' => 'प्रवेश आवश्यकताएं',
                'requirements_description' => 'प्रवेश के लिए आवश्यक दस्तावेज और जानकारी',
                'dates_badge' => 'समयसीमा',
                'dates_title' => 'महत्वपूर्ण तारीखें',
                'dates_description' => 'प्रवेश प्रक्रिया के लिए महत्वपूर्ण तारीखें',
                'faq_badge' => 'कोई सवाल?',
                'faq_title' => 'अक्सर पूछे जाने वाले प्रश्न',
                'faq_description' => 'हमारी प्रवेश प्रक्रिया के बारे में सामान्य प्रश्न',
                'cta_title' => 'अपनी यात्रा शुरू करने के लिए तैयार हैं?',
                'cta_description' => 'आज ही अपनी प्रवेश प्रक्रिया शुरू करें और हमारे जीवंत शिक्षा समुदाय में शामिल हों',
                'cta_button_text' => 'प्रवेश कार्यालय से संपर्क करें',
                'cta_button_text_2' => 'हमारे बारे में अधिक जानें',
            ],
            'kn' => [
                'hero_badge' => 'ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
                'hero_heading' => 'ಪ್ರವೇಶ ಮಾಹಿತಿ',
                'hero_description' => 'ನಮ್ಮ ಶಾಲಾ ಸಮುದಾಯಕ್ಕೆ ಸೇರಲು ನಮ್ಮ ಪ್ರವೇಶ ಪ್ರಕ್ರಿಯೆ ಮತ್ತು ಅವಶ್ಯಕತೆಗಳ ಬಗ್ಗೆ ತಿಳಿಯಿರಿ।',
                'process_badge' => 'ಹೇಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದು',
                'process_title' => 'ಪ್ರವೇಶ ಪ್ರಕ್ರಿಯೆ',
                'process_description' => 'ನಮ್ಮ ಶಾಲಾ ಸಮುದಾಯಕ್ಕೆ ಸೇರಲು ಸರಳ ಹಂತಗಳು',
                'requirements_badge' => 'ನಿಮಗೆ ಏನು ಬೇಕು',
                'requirements_title' => 'ಪ್ರವೇಶ ಅವಶ್ಯಕತೆಗಳು',
                'requirements_description' => 'ಪ್ರವೇಶಕ್ಕೆ ಅಗತ್ಯವಾದ ದಾಖಲೆಗಳು ಮತ್ತು ಮಾಹಿತಿ',
                'dates_badge' => 'ಸಮಯಸೀಮೆ',
                'dates_title' => 'ಮುಖ್ಯ ದಿನಾಂಕಗಳು',
                'dates_description' => 'ಪ್ರವೇಶ ಪ್ರಕ್ರಿಯೆಗೆ ಮುಖ್ಯ ದಿನಾಂಕಗಳು',
                'faq_badge' => 'ಪ್ರಶ್ನೆಗಳಿದ್ದರೆ?',
                'faq_title' => 'ಸಾಮಾನ್ಯವಾಗಿ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
                'faq_description' => 'ನಮ್ಮ ಪ್ರವೇಶ ಪ್ರಕ್ರಿಯೆ ಬಗ್ಗೆ ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು',
                'cta_title' => 'ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
                'cta_description' => 'ಇಂದೇ ನಿಮ್ಮ ಪ್ರವೇಶ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ ಮತ್ತು ನಮ್ಮ ಜೀವಂತ ಕಲಿಕೆ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
                'cta_button_text' => 'ಪ್ರವೇಶ ಕಚೇರಿಗೆ ಸಂಪರ್ಕಿಸಿ',
                'cta_button_text_2' => 'ನಮ್ಮ ಬಗ್ಗೆ ಹೆಚ್ಚು ತಿಳಿಯಿರಿ',
            ],
        ],
        'contact' => [
            'en' => [
                'hero_badge' => 'We\'re Here to Help',
                'hero_heading' => 'Contact Us',
                'hero_description' => 'Get in touch with us for any questions, inquiries, or to schedule a campus visit.',
                'form_badge' => 'Send Us a Message',
                'form_title' => 'Get In Touch',
                'form_description' => 'Fill out the form below and we\'ll get back to you as soon as possible.',
                'form_button_text' => 'Send Message',
                'contact_info_badge' => 'Contact Information',
                'contact_info_title' => 'Visit or Reach Us',
                'contact_info_description' => 'We\'re here to answer your questions and help you learn more about our school.',
                'address' => '123 School Street, Education City, State 12345',
                'phone' => '+1 (234) 567-890',
                'email' => 'info@school.com',
                'office_hours_title' => 'Office Hours',
                'office_hours_weekdays' => 'Monday - Friday: 8:00 AM - 5:00 PM',
                'office_hours_saturday' => 'Saturday: 9:00 AM - 1:00 PM',
                'office_hours_sunday' => 'Sunday: Closed',
                'map_badge' => 'Find Us',
                'map_title' => 'Location',
                'map_description' => 'Visit our campus or get directions',
                'map_embed_url' => '',
                'social_badge' => 'Connect With Us',
                'social_title' => 'Follow Our Journey',
                'social_description' => 'Stay connected through our social media channels',
            ],
            'hi' => [
                'hero_badge' => 'हम यहाँ मदद के लिए हैं',
                'hero_heading' => 'हमसे संपर्क करें',
                'hero_description' => 'किसी भी प्रश्न, पूछताछ या कैंपस भ्रमण की योजना बनाने के लिए हमसे संपर्क करें।',
                'form_badge' => 'हमें एक संदेश भेजें',
                'form_title' => 'संपर्क करें',
                'form_description' => 'नीचे दिया गया फॉर्म भरें और हम जल्द से जल्द आपसे संपर्क करेंगे।',
                'form_button_text' => 'संदेश भेजें',
                'contact_info_badge' => 'संपर्क जानकारी',
                'contact_info_title' => 'हमसे मिलें या संपर्क करें',
                'contact_info_description' => 'हम आपके प्रश्नों के उत्तर देने और आपको हमारे स्कूल के बारे में अधिक जानने में मदद करने के लिए यहाँ हैं।',
                'address' => '123 स्कूल स्ट्रीट, शिक्षा शहर, राज्य 12345',
                'phone' => '+1 (234) 567-890',
                'email' => 'info@school.com',
                'office_hours_title' => 'कार्यालय समय',
                'office_hours_weekdays' => 'सोमवार - शुक्रवार: सुबह 8:00 - शाम 5:00',
                'office_hours_saturday' => 'शनिवार: सुबह 9:00 - दोपहर 1:00',
                'office_hours_sunday' => 'रविवार: बंद',
                'map_badge' => 'हमें खोजें',
                'map_title' => 'स्थान',
                'map_description' => 'हमारे कैंपस का दौरा करें या दिशा-निर्देश प्राप्त करें',
                'map_embed_url' => '',
                'social_badge' => 'हमसे जुड़ें',
                'social_title' => 'हमारी यात्रा का अनुसरण करें',
                'social_description' => 'हमारे सोशल मीडिया चैनलों के माध्यम से जुड़े रहें',
            ],
            'kn' => [
                'hero_badge' => 'ನಾವು ಸಹಾಯಕ್ಕಾಗಿ ಇಲ್ಲಿದ್ದೇವೆ',
                'hero_heading' => 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
                'hero_description' => 'ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳು, ವಿಚಾರಣೆಗಳು ಅಥವಾ ಕ್ಯಾಂಪಸ್ ಭೇಟಿಯನ್ನು ನಿಗದಿಪಡಿಸಲು ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ।',
                'form_badge' => 'ನಮಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ',
                'form_title' => 'ಸಂಪರ್ಕಿಸಿ',
                'form_description' => 'ಕೆಳಗಿನ ಫಾರ್ಮ್ ಅನ್ನು ಭರ್ತಿ ಮಾಡಿ ಮತ್ತು ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
                'form_button_text' => 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
                'contact_info_badge' => 'ಸಂಪರ್ಕ ಮಾಹಿತಿ',
                'contact_info_title' => 'ನಮ್ಮನ್ನು ಭೇಟಿ ಮಾಡಿ ಅಥವಾ ಸಂಪರ್ಕಿಸಿ',
                'contact_info_description' => 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಲು ಮತ್ತು ನಮ್ಮ ಶಾಲೆಯ ಬಗ್ಗೆ ಹೆಚ್ಚು ತಿಳಿಯಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ನಾವು ಇಲ್ಲಿದ್ದೇವೆ.',
                'address' => '123 ಶಾಲೆ ರಸ್ತೆ, ಶಿಕ್ಷಣ ನಗರ, ರಾಜ್ಯ 12345',
                'phone' => '+1 (234) 567-890',
                'email' => 'info@school.com',
                'office_hours_title' => 'ಕಚೇರಿ ಸಮಯ',
                'office_hours_weekdays' => 'ಸೋಮವಾರ - ಶುಕ್ರವಾರ: ಬೆಳಿಗ್ಗೆ 8:00 - ಸಂಜೆ 5:00',
                'office_hours_saturday' => 'ಶನಿವಾರ: ಬೆಳಿಗ್ಗೆ 9:00 - ಮಧ್ಯಾಹ್ನ 1:00',
                'office_hours_sunday' => 'ಭಾನುವಾರ: ಮುಚ್ಚಿದೆ',
                'map_badge' => 'ನಮ್ಮನ್ನು ಹುಡುಕಿ',
                'map_title' => 'ಸ್ಥಳ',
                'map_description' => 'ನಮ್ಮ ಕ್ಯಾಂಪಸ್ಗೆ ಭೇಟಿ ನೀಡಿ ಅಥವಾ ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ',
                'map_embed_url' => '',
                'social_badge' => 'ನಮ್ಮೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ',
                'social_title' => 'ನಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಅನುಸರಿಸಿ',
                'social_description' => 'ನಮ್ಮ ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮ ಚಾನೆಲ್ಗಳ ಮೂಲಕ ಸಂಪರ್ಕದಲ್ಲಿರಿ',
            ],
        ],
    ],

    // Default components for home page
    'default_components' => [
        'features' => [
            [
                'title' => [
                    'en' => 'Academic Excellence',
                    'hi' => 'शैक्षणिक उत्कृष्टता',
                    'kn' => 'ಶೈಕ್ಷಣಿಕ ಶ್ರೇಷ್ಠತೆ',
                ],
                'description' => [
                    'en' => 'Comprehensive curriculum designed to challenge and inspire students to reach their highest potential through innovative teaching methods.',
                    'hi' => 'व्यापक पाठ्यक्रम जो नवाचारी शिक्षण विधियों के माध्यम से छात्रों को उनकी उच्चतम क्षमता तक पहुंचने के लिए चुनौती देने और प्रेरित करने के लिए डिज़ाइन किया गया है।',
                    'kn' => 'ನಾವೀನ್ಯತೆಯ ಕಲಿಕೆ ವಿಧಾನಗಳ ಮೂಲಕ ವಿದ್ಯಾರ್ಥಿಗಳು ತಮ್ಮ ಅತ್ಯುನ್ನತ ಸಾಮರ್ಥ್ಯವನ್ನು ತಲುಪಲು ಸವಾಲು ಮತ್ತು ಸ್ಫೂರ್ತಿ ನೀಡಲು ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ಸಮಗ್ರ ಪಠ್ಯಕ್ರಮ.',
                ],
                'icon' => 'book',
                'color' => 'primary',
            ],
            [
                'title' => [
                    'en' => 'Experienced Faculty',
                    'hi' => 'अनुभवी संकाय',
                    'kn' => 'ಅನುಭವಿ ಸಿಬ್ಬಂದಿ',
                ],
                'description' => [
                    'en' => 'Our dedicated teachers bring years of experience and passion for education to every classroom, ensuring personalized attention.',
                    'hi' => 'हमारे समर्पित शिक्षक हर कक्षा में वर्षों के अनुभव और शिक्षा के प्रति जुनून लाते हैं, व्यक्तिगत ध्यान सुनिश्चित करते हैं।',
                    'kn' => 'ನಮ್ಮ ಸಮರ್ಪಿತ ಶಿಕ್ಷಕರು ಪ್ರತಿ ತರಗತಿಗೆ ವರ್ಷಗಳ ಅನುಭವ ಮತ್ತು ಶಿಕ್ಷಣದ ಬಗ್ಗೆ ಉತ್ಸಾಹವನ್ನು ತರುತ್ತಾರೆ, ವೈಯಕ್ತಿಕ ಗಮನವನ್ನು ಖಚಿತಪಡಿಸುತ್ತಾರೆ.',
                ],
                'icon' => 'users',
                'color' => 'green',
            ],
            [
                'title' => [
                    'en' => 'Modern Facilities',
                    'hi' => 'आधुनिक सुविधाएं',
                    'kn' => 'ಆಧುನಿಕ ಸೌಲಭ್ಯಗಳು',
                ],
                'description' => [
                    'en' => 'State-of-the-art classrooms, laboratories, and recreational facilities to support holistic development of every student.',
                    'hi' => 'अत्याधुनिक कक्षाएं, प्रयोगशालाएं और मनोरंजन सुविधाएं प्रत्येक छात्र के समग्र विकास का समर्थन करने के लिए।',
                    'kn' => 'ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಯ ಸಮಗ್ರ ಅಭಿವೃದ್ಧಿಗೆ ಬೆಂಬಲಿಸಲು ಅತ್ಯಾಧುನಿಕ ತರಗತಿಗಳು, ಪ್ರಯೋಗಾಲಯಗಳು ಮತ್ತು ಮನರಂಜನಾ ಸೌಲಭ್ಯಗಳು.',
                ],
                'icon' => 'building',
                'color' => 'blue',
            ],
        ],
        'programs' => [
            [
                'title' => [
                    'en' => 'Primary School',
                    'hi' => 'प्राथमिक विद्यालय',
                    'kn' => 'ಪ್ರಾಥಮಿಕ ಶಾಲೆ',
                ],
                'subtitle' => [
                    'en' => 'Grades 1-5',
                    'hi' => 'कक्षा 1-5',
                    'kn' => 'ಗ್ರೇಡ್ 1-5',
                ],
                'description' => [
                    'en' => 'Foundation building programs',
                    'hi' => 'नींव निर्माण कार्यक्रम',
                    'kn' => 'ಅಡಿಪಾಯ ನಿರ್ಮಾಣ ಕಾರ್ಯಕ್ರಮಗಳು',
                ],
                'icon' => 'book',
                'color' => 'primary',
            ],
            [
                'title' => [
                    'en' => 'Middle School',
                    'hi' => 'मध्य विद्यालय',
                    'kn' => 'ಮಧ್ಯ ಶಾಲೆ',
                ],
                'subtitle' => [
                    'en' => 'Grades 6-8',
                    'hi' => 'कक्षा 6-8',
                    'kn' => 'ಗ್ರೇಡ್ 6-8',
                ],
                'description' => [
                    'en' => 'Critical thinking development',
                    'hi' => 'आलोचनात्मक सोच विकास',
                    'kn' => 'ವಿಮರ್ಶಾತ್ಮಕ ಚಿಂತನೆ ಅಭಿವೃದ್ಧಿ',
                ],
                'icon' => 'document-text',
                'color' => 'green',
            ],
            [
                'title' => [
                    'en' => 'High School',
                    'hi' => 'उच्च विद्यालय',
                    'kn' => 'ಹೈಸ್ಕೂಲ್',
                ],
                'subtitle' => [
                    'en' => 'Grades 9-12',
                    'hi' => 'कक्षा 9-12',
                    'kn' => 'ಗ್ರೇಡ್ 9-12',
                ],
                'description' => [
                    'en' => 'College preparation focus',
                    'hi' => 'कॉलेज तैयारी फोकस',
                    'kn' => 'ಕಾಲೇಜು ತಯಾರಿ ಫೋಕಸ್',
                ],
                'icon' => 'academic-cap',
                'color' => 'blue',
            ],
            [
                'title' => [
                    'en' => 'Special Programs',
                    'hi' => 'विशेष कार्यक्रम',
                    'kn' => 'ವಿಶೇಷ ಕಾರ್ಯಕ್ರಮಗಳು',
                ],
                'subtitle' => [
                    'en' => 'Arts, Sports, STEM',
                    'hi' => 'कला, खेल, STEM',
                    'kn' => 'ಕಲೆ, ಕ್ರೀಡೆ, STEM',
                ],
                'description' => [
                    'en' => 'Extracurricular excellence',
                    'hi' => 'पाठ्येतर उत्कृष्टता',
                    'kn' => 'ಪಠ್ಯೇತರ ಶ್ರೇಷ್ಠತೆ',
                ],
                'icon' => 'sparkles',
                'color' => 'purple',
            ],
        ],
        'program_cards' => [
            [
                'title' => [
                    'en' => 'Elementary Education',
                    'hi' => 'प्राथमिक शिक्षा',
                    'kn' => 'ಪ್ರಾಥಮಿಕ ಶಿಕ್ಷಣ',
                ],
                'description' => [
                    'en' => 'Foundational learning program for grades 1-5, focusing on building strong academic fundamentals and developing critical thinking skills.',
                    'hi' => 'ग्रेड 1-5 के लिए मौलिक शिक्षण कार्यक्रम, मजबूत शैक्षणिक मूल बातें बनाने और महत्वपूर्ण सोच कौशल विकसित करने पर ध्यान केंद्रित करता है।',
                    'kn' => 'ಗ್ರೇಡ್ 1-5 ಗಾಗಿ ಮೂಲಭೂತ ಕಲಿಕೆ ಕಾರ್ಯಕ್ರಮ, ಬಲವಾದ ಶೈಕ್ಷಣಿಕ ಮೂಲಭೂತಗಳನ್ನು ನಿರ್ಮಿಸುವುದು ಮತ್ತು ವಿಮರ್ಶಾತ್ಮಕ ಚಿಂತನೆಯ ಕೌಶಲ್ಯಗಳನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸುವುದರ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ.',
                ],
                'features' => [
                    'en' => ['Age-appropriate curriculum', 'Interactive learning methods', 'Character development'],
                    'hi' => ['उम्र-उपयुक्त पाठ्यक्रम', 'इंटरैक्टिव शिक्षण विधियां', 'चरित्र विकास'],
                    'kn' => ['ವಯಸ್ಸಿಗೆ ಸೂಕ್ತವಾದ ಪಠ್ಯಕ್ರಮ', 'ಸಂವಾದಾತ್ಮಕ ಕಲಿಕೆ ವಿಧಾನಗಳು', 'ಚಾರಿತ್ರಿಕ ಅಭಿವೃದ್ಧಿ'],
                ],
                'icon' => 'book',
                'color' => 'blue',
                'url' => '/admission',
            ],
            [
                'title' => [
                    'en' => 'Middle School',
                    'hi' => 'मध्य विद्यालय',
                    'kn' => 'ಮಧ್ಯ ಶಾಲೆ',
                ],
                'description' => [
                    'en' => 'Comprehensive program for grades 6-8, emphasizing subject specialization, research skills, and independent learning.',
                    'hi' => 'ग्रेड 6-8 के लिए व्यापक कार्यक्रम, विषय विशेषज्ञता, अनुसंधान कौशल और स्वतंत्र शिक्षा पर जोर देता है।',
                    'kn' => 'ಗ್ರೇಡ್ 6-8 ಗಾಗಿ ಸಮಗ್ರ ಕಾರ್ಯಕ್ರಮ, ವಿಷಯ ವಿಶೇಷೀಕರಣ, ಸಂಶೋಧನಾ ಕೌಶಲ್ಯಗಳು ಮತ್ತು ಸ್ವತಂತ್ರ ಕಲಿಕೆಯ ಮೇಲೆ ಒತ್ತು ನೀಡುತ್ತದೆ.',
                ],
                'features' => [
                    'en' => ['Subject specialization', 'Research & project work', 'Leadership opportunities'],
                    'hi' => ['विषय विशेषज्ञता', 'अनुसंधान और परियोजना कार्य', 'नेतृत्व के अवसर'],
                    'kn' => ['ವಿಷಯ ವಿಶೇಷೀಕರಣ', 'ಸಂಶೋಧನೆ ಮತ್ತು ಯೋಜನೆ ಕೆಲಸ', 'ನೇತೃತ್ವದ ಅವಕಾಶಗಳು'],
                ],
                'icon' => 'document-text',
                'color' => 'green',
                'url' => '/admission',
            ],
            [
                'title' => [
                    'en' => 'High School',
                    'hi' => 'उच्च विद्यालय',
                    'kn' => 'ಹೈಸ್ಕೂಲ್',
                ],
                'description' => [
                    'en' => 'Advanced program for grades 9-12, preparing students for higher education and career success through rigorous academics.',
                    'hi' => 'ग्रेड 9-12 के लिए उन्नत कार्यक्रम, कठोर शैक्षणिकता के माध्यम से छात्रों को उच्च शिक्षा और करियर सफलता के लिए तैयार करता है।',
                    'kn' => 'ಗ್ರೇಡ್ 9-12 ಗಾಗಿ ಮುಂದುವರಿದ ಕಾರ್ಯಕ್ರಮ, ಕಠಿಣ ಶೈಕ್ಷಣಿಕತೆಯ ಮೂಲಕ ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಉನ್ನತ ಶಿಕ್ಷಣ ಮತ್ತು ವೃತ್ತಿ ಯಶಸ್ಸಿಗಾಗಿ ಸಿದ್ಧಪಡಿಸುತ್ತದೆ.',
                ],
                'features' => [
                    'en' => ['College preparation', 'Advanced placement courses', 'Career counseling'],
                    'hi' => ['कॉलेज तैयारी', 'उन्नत प्लेसमेंट पाठ्यक्रम', 'करियर परामर्श'],
                    'kn' => ['ಕಾಲೇಜು ತಯಾರಿ', 'ಮುಂದುವರಿದ ಪ್ಲೇಸ್ಮೆಂಟ್ ಕೋರ್ಸ್ಗಳು', 'ವೃತ್ತಿ ಸಲಹೆ'],
                ],
                'icon' => 'academic-cap',
                'color' => 'purple',
                'url' => '/admission',
            ],
            [
                'title' => [
                    'en' => 'STEM Program',
                    'hi' => 'STEM कार्यक्रम',
                    'kn' => 'STEM ಕಾರ್ಯಕ್ರಮ',
                ],
                'description' => [
                    'en' => 'Specialized Science, Technology, Engineering, and Mathematics program fostering innovation and problem-solving skills.',
                    'hi' => 'विशेष विज्ञान, प्रौद्योगिकी, इंजीनियरिंग और गणित कार्यक्रम नवाचार और समस्या-समाधान कौशल को बढ़ावा देता है।',
                    'kn' => 'ವಿಶೇಷ ವಿಜ್ಞಾನ, ತಂತ್ರಜ್ಞಾನ, ಎಂಜಿನಿಯರಿಂಗ್ ಮತ್ತು ಗಣಿತ ಕಾರ್ಯಕ್ರಮ ನಾವೀನ್ಯತೆ ಮತ್ತು ಸಮಸ್ಯೆ-ಪರಿಹಾರ ಕೌಶಲ್ಯಗಳನ್ನು ಉತ್ತೇಜಿಸುತ್ತದೆ.',
                ],
                'features' => [
                    'en' => ['Hands-on experiments', 'Technology integration', 'Competition participation'],
                    'hi' => ['हाथों से प्रयोग', 'प्रौद्योगिकी एकीकरण', 'प्रतियोगिता भागीदारी'],
                    'kn' => ['ಕೈಗಳಿಂದ ಪ್ರಯೋಗಗಳು', 'ತಂತ್ರಜ್ಞಾನ ಏಕೀಕರಣ', 'ಸ್ಪರ್ಧೆ ಭಾಗವಹಿಸುವಿಕೆ'],
                ],
                'icon' => 'sparkles',
                'color' => 'orange',
                'url' => '/admission',
            ],
            [
                'title' => [
                    'en' => 'Arts & Music',
                    'hi' => 'कला और संगीत',
                    'kn' => 'ಕಲೆ ಮತ್ತು ಸಂಗೀತ',
                ],
                'description' => [
                    'en' => 'Creative arts program nurturing artistic expression, musical talent, and cultural appreciation in students.',
                    'hi' => 'रचनात्मक कला कार्यक्रम छात्रों में कलात्मक अभिव्यक्ति, संगीत प्रतिभा और सांस्कृतिक प्रशंसा को बढ़ावा देता है।',
                    'kn' => 'ಸೃಜನಶೀಲ ಕಲೆ ಕಾರ್ಯಕ್ರಮ ವಿದ್ಯಾರ್ಥಿಗಳಲ್ಲಿ ಕಲಾತ್ಮಕ ಅಭಿವ್ಯಕ್ತಿ, ಸಂಗೀತ ಪ್ರತಿಭೆ ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಮೆಚ್ಚುಗೆಯನ್ನು ಪೋಷಿಸುತ್ತದೆ.',
                ],
                'features' => [
                    'en' => ['Visual arts classes', 'Music & performance', 'Annual showcases'],
                    'hi' => ['दृश्य कला कक्षाएं', 'संगीत और प्रदर्शन', 'वार्षिक प्रदर्शनियां'],
                    'kn' => ['ದೃಶ್ಯ ಕಲೆ ತರಗತಿಗಳು', 'ಸಂಗೀತ ಮತ್ತು ಪ್ರದರ್ಶನ', 'ವಾರ್ಷಿಕ ಪ್ರದರ್ಶನಿಗಳು'],
                ],
                'icon' => 'music',
                'color' => 'red',
                'url' => '/admission',
            ],
            [
                'title' => [
                    'en' => 'Sports & Athletics',
                    'hi' => 'खेल और एथलेटिक्स',
                    'kn' => 'ಕ್ರೀಡೆ ಮತ್ತು ಅಥ್ಲೆಟಿಕ್ಸ್',
                ],
                'description' => [
                    'en' => 'Comprehensive sports program promoting physical fitness, teamwork, and competitive excellence across multiple disciplines.',
                    'hi' => 'व्यापक खेल कार्यक्रम कई विषयों में शारीरिक फिटनेस, टीम वर्क और प्रतिस्पर्धी उत्कृष्टता को बढ़ावा देता है।',
                    'kn' => 'ಸಮಗ್ರ ಕ್ರೀಡೆ ಕಾರ್ಯಕ್ರಮವು ಹಲವಾರು ವಿಭಾಗಗಳಲ್ಲಿ ದೈಹಿಕ ಫಿಟ್ನೆಸ್, ತಂಡ ಕೆಲಸ ಮತ್ತು ಸ್ಪರ್ಧಾತ್ಮಕ ಶ್ರೇಷ್ಠತೆಯನ್ನು ಉತ್ತೇಜಿಸುತ್ತದೆ.',
                ],
                'features' => [
                    'en' => ['Multiple sports options', 'Professional coaching', 'Inter-school competitions'],
                    'hi' => ['कई खेल विकल्प', 'पेशेवर कोचिंग', 'अंतर-स्कूल प्रतियोगिताएं'],
                    'kn' => ['ಹಲವಾರು ಕ್ರೀಡೆ ಆಯ್ಕೆಗಳು', 'ವೃತ್ತಿಪರ ತರಬೇತಿ', 'ಅಂತರ-ಶಾಲೆ ಸ್ಪರ್ಧೆಗಳು'],
                ],
                'icon' => 'users',
                'color' => 'indigo',
                'url' => '/admission',
            ],
        ],
        'testimonials' => [
            [
                'title' => [],
                'description' => [
                    'en' => 'The best decision we made for our child\'s education. The teachers are dedicated and the facilities are outstanding.',
                    'hi' => 'हमने अपने बच्चे की शिक्षा के लिए सबसे अच्छा निर्णय लिया। शिक्षक समर्पित हैं और सुविधाएं उत्कृष्ट हैं।',
                    'kn' => 'ನಮ್ಮ ಮಗುವಿನ ಶಿಕ್ಷಣಕ್ಕಾಗಿ ನಾವು ತೆಗೆದುಕೊಂಡ ಉತ್ತಮ ನಿರ್ಣಯ. ಶಿಕ್ಷಕರು ಸಮರ್ಪಿತರಾಗಿದ್ದಾರೆ ಮತ್ತು ಸೌಲಭ್ಯಗಳು ಅತ್ಯುತ್ತಮವಾಗಿವೆ.',
                ],
                'author_name' => 'Sarah Mitchell',
                'author_role' => 'Parent',
                'author_initials' => 'SM',
                'rating' => 5,
                'color' => 'primary',
            ],
            [
                'title' => [],
                'description' => [
                    'en' => 'Excellent academic standards and a nurturing environment. Our daughter has flourished here beyond our expectations.',
                    'hi' => 'उत्कृष्ट शैक्षणिक मानक और एक पोषण वातावरण। हमारी बेटी यहाँ हमारी अपेक्षाओं से कहीं अधिक फलीभूत हुई है।',
                    'kn' => 'ಉತ್ಕೃಷ್ಟ ಶೈಕ್ಷಣಿಕ ಮಾನದಂಡಗಳು ಮತ್ತು ಪೋಷಕ ವಾತಾವರಣ. ನಮ್ಮ ಮಗಳು ನಮ್ಮ ನಿರೀಕ್ಷೆಗಳನ್ನು ಮೀರಿ ಇಲ್ಲಿ ಅಭಿವೃದ್ಧಿ ಹೊಂದಿದ್ದಾಳೆ.',
                ],
                'author_name' => 'John Davis',
                'author_role' => 'Parent',
                'author_initials' => 'JD',
                'rating' => 5,
                'color' => 'green',
            ],
            [
                'title' => [],
                'description' => [
                    'en' => 'Outstanding support system and amazing teachers. The school prepares students for success in all aspects of life.',
                    'hi' => 'उत्कृष्ट सहायता प्रणाली और अद्भुत शिक्षक। स्कूल छात्रों को जीवन के सभी पहलुओं में सफलता के लिए तैयार करता है।',
                    'kn' => 'ಉತ್ಕೃಷ್ಟ ಬೆಂಬಲ ವ್ಯವಸ್ಥೆ ಮತ್ತು ಅದ್ಭುತ ಶಿಕ್ಷಕರು. ಶಾಲೆಯು ವಿದ್ಯಾರ್ಥಿಗಳನ್ನು ಜೀವನದ ಎಲ್ಲಾ ಅಂಶಗಳಲ್ಲಿ ಯಶಸ್ಸಿಗಾಗಿ ಸಿದ್ಧಪಡಿಸುತ್ತದೆ.',
                ],
                'author_name' => 'Emma Wilson',
                'author_role' => 'Parent',
                'author_initials' => 'EW',
                'rating' => 5,
                'color' => 'blue',
            ],
        ],
        'quick_links' => [
            [
                'title' => [
                    'en' => 'Admission',
                    'hi' => 'प्रवेश',
                    'kn' => 'ಪ್ರವೇಶ',
                ],
                'description' => [
                    'en' => 'Apply now',
                    'hi' => 'अभी आवेदन करें',
                    'kn' => 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
                ],
                'url' => '/admission',
                'icon' => 'document-text',
                'color' => 'primary',
            ],
            [
                'title' => [
                    'en' => 'Programs',
                    'hi' => 'कार्यक्रम',
                    'kn' => 'ಕಾರ್ಯಕ್ರಮಗಳು',
                ],
                'description' => [
                    'en' => 'View courses',
                    'hi' => 'पाठ्यक्रम देखें',
                    'kn' => 'ಕೋರ್ಸ್ಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
                ],
                'url' => '/programs',
                'icon' => 'book-open',
                'color' => 'green',
            ],
            [
                'title' => [
                    'en' => 'Facilities',
                    'hi' => 'सुविधाएं',
                    'kn' => 'ಸೌಲಭ್ಯಗಳು',
                ],
                'description' => [
                    'en' => 'Explore campus',
                    'hi' => 'कैंपस देखें',
                    'kn' => 'ಕ್ಯಾಂಪಸ್ ಅನ್ವೇಷಿಸಿ',
                ],
                'url' => '/facilities',
                'icon' => 'building-office',
                'color' => 'blue',
            ],
            [
                'title' => [
                    'en' => 'Contact',
                    'hi' => 'संपर्क',
                    'kn' => 'ಸಂಪರ್ಕ',
                ],
                'description' => [
                    'en' => 'Get in touch',
                    'hi' => 'संपर्क करें',
                    'kn' => 'ಸಂಪರ್ಕಿಸಿ',
                ],
                'url' => '/contact',
                'icon' => 'envelope',
                'color' => 'purple',
            ],
        ],
        'facility_cards' => [
            [
                'title' => [
                    'en' => 'Modern Library',
                    'hi' => 'आधुनिक पुस्तकालय',
                    'kn' => 'ಆಧುನಿಕ ಗ್ರಂಥಾಲಯ',
                ],
                'description' => [
                    'en' => 'Extensive collection of books, digital resources, and quiet study spaces for research and learning.',
                    'hi' => 'अनुसंधान और सीखने के लिए पुस्तकों, डिजिटल संसाधनों और शांत अध्ययन स्थानों का व्यापक संग्रह।',
                    'kn' => 'ಸಂಶೋಧನೆ ಮತ್ತು ಕಲಿಕೆಗಾಗಿ ಪುಸ್ತಕಗಳು, ಡಿಜಿಟಲ್ ಸಂಪನ್ಮೂಲಗಳು ಮತ್ತು ಶಾಂತ ಅಧ್ಯಯನ ಸ್ಥಳಗಳ ವ್ಯಾಪಕ ಸಂಗ್ರಹ.',
                ],
                'features' => [
                    'en' => ['50,000+ books collection', 'Digital reading resources', 'Quiet study zones'],
                    'hi' => ['50,000+ पुस्तक संग्रह', 'डिजिटल पढ़ने के संसाधन', 'शांत अध्ययन क्षेत्र'],
                    'kn' => ['50,000+ ಪುಸ್ತಕಗಳ ಸಂಗ್ರಹ', 'ಡಿಜಿಟಲ್ ಓದುವಿಕೆ ಸಂಪನ್ಮೂಲಗಳು', 'ಶಾಂತ ಅಧ್ಯಯನ ವಲಯಗಳು'],
                ],
                'icon' => 'book',
                'color' => 'blue',
            ],
            [
                'title' => [
                    'en' => 'Science Laboratories',
                    'hi' => 'विज्ञान प्रयोगशालाएं',
                    'kn' => 'ವಿಜ್ಞಾನ ಪ್ರಯೋಗಾಲಯಗಳು',
                ],
                'description' => [
                    'en' => 'Fully equipped labs for Physics, Chemistry, and Biology with modern equipment and safety measures.',
                    'hi' => 'आधुनिक उपकरण और सुरक्षा उपायों के साथ भौतिकी, रसायन विज्ञान और जीव विज्ञान के लिए पूरी तरह से सुसज्जित प्रयोगशालाएं।',
                    'kn' => 'ಆಧುನಿಕ ಉಪಕರಣಗಳು ಮತ್ತು ಸುರಕ್ಷತಾ ಕ್ರಮಗಳೊಂದಿಗೆ ಭೌತಶಾಸ್ತ್ರ, ರಸಾಯನಶಾಸ್ತ್ರ ಮತ್ತು ಜೀವಶಾಸ್ತ್ರಕ್ಕಾಗಿ ಸಂಪೂರ್ಣವಾಗಿ ಸಜ್ಜುಗೊಳಿಸಲಾದ ಪ್ರಯೋಗಾಲಯಗಳು.',
                ],
                'features' => [
                    'en' => ['Physics, Chemistry, Biology labs', 'Modern equipment & tools', 'Safety-certified facilities'],
                    'hi' => ['भौतिकी, रसायन विज्ञान, जीव विज्ञान प्रयोगशालाएं', 'आधुनिक उपकरण और उपकरण', 'सुरक्षा-प्रमाणित सुविधाएं'],
                    'kn' => ['ಭೌತಶಾಸ್ತ್ರ, ರಸಾಯನಶಾಸ್ತ್ರ, ಜೀವಶಾಸ್ತ್ರ ಪ್ರಯೋಗಾಲಯಗಳು', 'ಆಧುನಿಕ ಉಪಕರಣಗಳು ಮತ್ತು ಉಪಕರಣಗಳು', 'ಸುರಕ್ಷತೆ-ಪ್ರಮಾಣೀಕೃತ ಸೌಲಭ್ಯಗಳು'],
                ],
                'icon' => 'flask',
                'color' => 'purple',
            ],
            [
                'title' => [
                    'en' => 'Computer Labs',
                    'hi' => 'कंप्यूटर प्रयोगशालाएं',
                    'kn' => 'ಕಂಪ್ಯೂಟರ್ ಪ್ರಯೋಗಾಲಯಗಳು',
                ],
                'description' => [
                    'en' => 'High-tech computer laboratories with latest hardware and software for digital learning and programming.',
                    'hi' => 'डिजिटल सीखने और प्रोग्रामिंग के लिए नवीनतम हार्डवेयर और सॉफ्टवेयर के साथ उच्च तकनीक कंप्यूटर प्रयोगशालाएं।',
                    'kn' => 'ಡಿಜಿಟಲ್ ಕಲಿಕೆ ಮತ್ತು ಪ್ರೋಗ್ರಾಮಿಂಗ್ಗಾಗಿ ನವೀನ ಹಾರ್ಡ್ವೇರ್ ಮತ್ತು ಸಾಫ್ಟ್ವೇರ್ನೊಂದಿಗೆ ಹೈ-ಟೆಕ್ ಕಂಪ್ಯೂಟರ್ ಪ್ರಯೋಗಾಲಯಗಳು.',
                ],
                'features' => [
                    'en' => ['Latest hardware & software', 'High-speed internet', 'Programming & coding tools'],
                    'hi' => ['नवीनतम हार्डवेयर और सॉफ्टवेयर', 'हाई-स्पीड इंटरनेट', 'प्रोग्रामिंग और कोडिंग उपकरण'],
                    'kn' => ['ನವೀನ ಹಾರ್ಡ್ವೇರ್ ಮತ್ತು ಸಾಫ್ಟ್ವೇರ್', 'ಹೈ-ಸ್ಪೀಡ್ ಇಂಟರ್ನೆಟ್', 'ಪ್ರೋಗ್ರಾಮಿಂಗ್ ಮತ್ತು ಕೋಡಿಂಗ್ ಉಪಕರಣಗಳು'],
                ],
                'icon' => 'computer',
                'color' => 'indigo',
            ],
            [
                'title' => [
                    'en' => 'Sports Complex',
                    'hi' => 'खेल परिसर',
                    'kn' => 'ಕ್ರೀಡಾ ಸಂಕೀರ್ಣ',
                ],
                'description' => [
                    'en' => 'Comprehensive sports facilities including indoor and outdoor courts, fields, and fitness centers.',
                    'hi' => 'इनडोर और आउटडोर कोर्ट, मैदान और फिटनेस सेंटर सहित व्यापक खेल सुविधाएं।',
                    'kn' => 'ಒಳಾಂಗಣ ಮತ್ತು ಹೊರಾಂಗಣ ಕೋರ್ಟ್ಗಳು, ಕ್ಷೇತ್ರಗಳು ಮತ್ತು ಫಿಟ್ನೆಸ್ ಕೇಂದ್ರಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಸಮಗ್ರ ಕ್ರೀಡಾ ಸೌಲಭ್ಯಗಳು.',
                ],
                'features' => [
                    'en' => ['Basketball & volleyball courts', 'Football & cricket fields', 'Fitness & gymnasium'],
                    'hi' => ['बास्केटबॉल और वॉलीबॉल कोर्ट', 'फुटबॉल और क्रिकेट मैदान', 'फिटनेस और जिमनैजियम'],
                    'kn' => ['ಬ್ಯಾಸ್ಕೆಟ್ಬಾಲ್ ಮತ್ತು ವಾಲಿಬಾಲ್ ಕೋರ್ಟ್ಗಳು', 'ಫುಟ್ಬಾಲ್ ಮತ್ತು ಕ್ರಿಕೆಟ್ ಕ್ಷೇತ್ರಗಳು', 'ಫಿಟ್ನೆಸ್ ಮತ್ತು ಜಿಮ್ನೇಜಿಯಂ'],
                ],
                'icon' => 'sport',
                'color' => 'green',
            ],
            [
                'title' => [
                    'en' => 'Auditorium',
                    'hi' => 'सभागार',
                    'kn' => 'ಸಭಾಂಗಣ',
                ],
                'description' => [
                    'en' => 'Spacious auditorium with modern audio-visual equipment for assemblies, performances, and events.',
                    'hi' => 'सभाओं, प्रदर्शनों और कार्यक्रमों के लिए आधुनिक ऑडियो-विज़ुअल उपकरणों के साथ विशाल सभागार।',
                    'kn' => 'ಸಭೆಗಳು, ಪ್ರದರ್ಶನಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ರಮಗಳಿಗಾಗಿ ಆಧುನಿಕ ಆಡಿಯೋ-ವಿಷುವಲ್ ಉಪಕರಣಗಳೊಂದಿಗೆ ವಿಶಾಲ ಸಭಾಂಗಣ.',
                ],
                'features' => [
                    'en' => ['500+ seating capacity', 'Advanced sound system', 'Stage & lighting setup'],
                    'hi' => ['500+ बैठने की क्षमता', 'उन्नत ध्वनि प्रणाली', 'मंच और प्रकाश व्यवस्था'],
                    'kn' => ['500+ ಆಸನ ಸಾಮರ್ಥ್ಯ', 'ಮುಂದುವರಿದ ಧ್ವನಿ ವ್ಯವಸ್ಥೆ', 'ವೇದಿಕೆ ಮತ್ತು ಬೆಳಕಿನ ಸೆಟಪ್'],
                ],
                'icon' => 'video',
                'color' => 'red',
            ],
            [
                'title' => [
                    'en' => 'Cafeteria',
                    'hi' => 'कैफेटेरिया',
                    'kn' => 'ಕ್ಯಾಫೆಟೇರಿಯಾ',
                ],
                'description' => [
                    'en' => 'Clean and spacious dining area serving healthy, nutritious meals prepared in hygienic conditions.',
                    'hi' => 'स्वच्छ और विशाल भोजन क्षेत्र स्वच्छ परिस्थितियों में तैयार स्वस्थ, पौष्टिक भोजन परोसता है।',
                    'kn' => 'ಸ್ವಚ್ಛ ಮತ್ತು ವಿಶಾಲ ಊಟದ ಪ್ರದೇಶವು ನೈರ್ಮಲ್ಯ ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ ತಯಾರಿಸಿದ ಆರೋಗ್ಯಕರ, ಪೌಷ್ಟಿಕ ಆಹಾರವನ್ನು ಸೇವಿಸುತ್ತದೆ.',
                ],
                'features' => [
                    'en' => ['Healthy meal options', 'Hygienic food preparation', 'Comfortable seating area'],
                    'hi' => ['स्वस्थ भोजन विकल्प', 'स्वच्छ भोजन तैयारी', 'आरामदायक बैठने का क्षेत्र'],
                    'kn' => ['ಆರೋಗ್ಯಕರ ಆಹಾರ ಆಯ್ಕೆಗಳು', 'ನೈರ್ಮಲ್ಯ ಆಹಾರ ತಯಾರಿಕೆ', 'ಆರಾಮದಾಯಕ ಆಸನ ಪ್ರದೇಶ'],
                ],
                'icon' => 'utensils',
                'color' => 'orange',
            ],
            [
                'title' => [
                    'en' => 'Art & Craft Room',
                    'hi' => 'कला और शिल्प कक्ष',
                    'kn' => 'ಕಲೆ ಮತ್ತು ಕರಕುಶಲ ಕೊಠಡಿ',
                ],
                'description' => [
                    'en' => 'Dedicated space for creative expression with art supplies, tools, and display areas for student artwork.',
                    'hi' => 'छात्र कलाकृतियों के लिए कला आपूर्ति, उपकरण और प्रदर्शन क्षेत्रों के साथ रचनात्मक अभिव्यक्ति के लिए समर्पित स्थान।',
                    'kn' => 'ವಿದ್ಯಾರ್ಥಿ ಕಲಾಕೃತಿಗಳಿಗಾಗಿ ಕಲಾ ಸರಬರಾಜು, ಉಪಕರಣಗಳು ಮತ್ತು ಪ್ರದರ್ಶನ ಪ್ರದೇಶಗಳೊಂದಿಗೆ ಸೃಜನಶೀಲ ಅಭಿವ್ಯಕ್ತಿಗಾಗಿ ಸಮರ್ಪಿತ ಸ್ಥಳ.',
                ],
                'features' => [
                    'en' => ['Complete art supplies', 'Pottery & sculpture tools', 'Artwork display gallery'],
                    'hi' => ['पूर्ण कला आपूर्ति', 'मिट्टी के बर्तन और मूर्तिकला उपकरण', 'कलाकृति प्रदर्शन गैलरी'],
                    'kn' => ['ಸಂಪೂರ್ಣ ಕಲಾ ಸರಬರಾಜು', 'ಮಡಕೆ ಮತ್ತು ಶಿಲ್ಪಕಲೆ ಉಪಕರಣಗಳು', 'ಕಲಾಕೃತಿ ಪ್ರದರ್ಶನ ಗ್ಯಾಲರಿ'],
                ],
                'icon' => 'brush',
                'color' => 'pink',
            ],
            [
                'title' => [
                    'en' => 'Music Room',
                    'hi' => 'संगीत कक्ष',
                    'kn' => 'ಸಂಗೀತ ಕೊಠಡಿ',
                ],
                'description' => [
                    'en' => 'Soundproof music room equipped with various instruments and audio equipment for music education.',
                    'hi' => 'संगीत शिक्षा के लिए विभिन्न वाद्ययंत्रों और ऑडियो उपकरणों से सुसज्जित ध्वनिरोधी संगीत कक्ष।',
                    'kn' => 'ಸಂಗೀತ ಶಿಕ್ಷಣಕ್ಕಾಗಿ ವಿವಿಧ ವಾದ್ಯಗಳು ಮತ್ತು ಆಡಿಯೋ ಉಪಕರಣಗಳೊಂದಿಗೆ ಸಜ್ಜುಗೊಳಿಸಲಾದ ಧ್ವನಿರೋಧಕ ಸಂಗೀತ ಕೊಠಡಿ.',
                ],
                'features' => [
                    'en' => ['Various musical instruments', 'Soundproof environment', 'Recording facilities'],
                    'hi' => ['विभिन्न संगीत वाद्ययंत्र', 'ध्वनिरोधी वातावरण', 'रिकॉर्डिंग सुविधाएं'],
                    'kn' => ['ವಿವಿಧ ಸಂಗೀತ ವಾದ್ಯಗಳು', 'ಧ್ವನಿರೋಧಕ ವಾತಾವರಣ', 'ರೆಕಾರ್ಡಿಂಗ್ ಸೌಲಭ್ಯಗಳು'],
                ],
                'icon' => 'music',
                'color' => 'teal',
            ],
            [
                'title' => [
                    'en' => 'Medical Room',
                    'hi' => 'चिकित्सा कक्ष',
                    'kn' => 'ವೈದ್ಯಕೀಯ ಕೊಠಡಿ',
                ],
                'description' => [
                    'en' => 'Well-equipped medical facility with trained staff to handle emergencies and provide first aid.',
                    'hi' => 'आपात स्थितियों को संभालने और प्राथमिक चिकित्सा प्रदान करने के लिए प्रशिक्षित स्टाफ के साथ अच्छी तरह से सुसज्जित चिकित्सा सुविधा।',
                    'kn' => 'ಅನಾಹುತಗಳನ್ನು ನಿಭಾಯಿಸಲು ಮತ್ತು ಪ್ರಥಮ ಚಿಕಿತ್ಸೆಯನ್ನು ಒದಗಿಸಲು ತರಬೇತಿ ಪಡೆದ ಸಿಬ್ಬಂದಿಯೊಂದಿಗೆ ಚೆನ್ನಾಗಿ ಸಜ್ಜುಗೊಳಿಸಲಾದ ವೈದ್ಯಕೀಯ ಸೌಲಭ್ಯ.',
                ],
                'features' => [
                    'en' => ['Qualified medical staff', 'First aid equipment', '24/7 emergency support'],
                    'hi' => ['योग्य चिकित्सा स्टाफ', 'प्राथमिक चिकित्सा उपकरण', '24/7 आपातकालीन सहायता'],
                    'kn' => ['ಅರ್ಹ ವೈದ್ಯಕೀಯ ಸಿಬ್ಬಂದಿ', 'ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಉಪಕರಣ', '24/7 ಅನಾಹುತ ಬೆಂಬಲ'],
                ],
                'icon' => 'heart',
                'color' => 'cyan',
            ],
        ],
        'amenity_cards' => [
            [
                'title' => [
                    'en' => 'Smart Classrooms',
                    'hi' => 'स्मार्ट कक्षाएं',
                    'kn' => 'ಸ್ಮಾರ್ಟ್ ತರಗತಿಗಳು',
                ],
                'description' => [
                    'en' => 'Interactive whiteboards and digital learning tools',
                    'hi' => 'इंटरैक्टिव व्हाइटबोर्ड और डिजिटल सीखने के उपकरण',
                    'kn' => 'ಸಂವಾದಾತ್ಮಕ ವೈಟ್ಬೋರ್ಡ್ಗಳು ಮತ್ತು ಡಿಜಿಟಲ್ ಕಲಿಕೆ ಉಪಕರಣಗಳು',
                ],
                'icon' => 'device',
                'color' => 'blue',
            ],
            [
                'title' => [
                    'en' => 'Security System',
                    'hi' => 'सुरक्षा प्रणाली',
                    'kn' => 'ಭದ್ರತಾ ವ್ಯವಸ್ಥೆ',
                ],
                'description' => [
                    'en' => '24/7 surveillance and access control',
                    'hi' => '24/7 निगरानी और पहुंच नियंत्रण',
                    'kn' => '24/7 ನಿಗಾವಣೆ ಮತ್ತು ಪ್ರವೇಶ ನಿಯಂತ್ರಣ',
                ],
                'icon' => 'shield',
                'color' => 'green',
            ],
            [
                'title' => [
                    'en' => 'Wi-Fi Campus',
                    'hi' => 'वाई-फाई कैंपस',
                    'kn' => 'ವೈ-ಫೈ ಕ್ಯಾಂಪಸ್',
                ],
                'description' => [
                    'en' => 'High-speed internet throughout the campus',
                    'hi' => 'पूरे कैंपस में हाई-स्पीड इंटरनेट',
                    'kn' => 'ಕ್ಯಾಂಪಸ್ ಮೂಲಕ ಹೈ-ಸ್ಪೀಡ್ ಇಂಟರ್ನೆಟ್',
                ],
                'icon' => 'wifi',
                'color' => 'purple',
            ],
            [
                'title' => [
                    'en' => 'Transportation',
                    'hi' => 'परिवहन',
                    'kn' => 'ಸಾರಿಗೆ',
                ],
                'description' => [
                    'en' => 'Safe and reliable school bus service',
                    'hi' => 'सुरक्षित और विश्वसनीय स्कूल बस सेवा',
                    'kn' => 'ಸುರಕ್ಷಿತ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ ಶಾಲಾ ಬಸ್ ಸೇವೆ',
                ],
                'icon' => 'bus',
                'color' => 'orange',
            ],
        ],
        'process_steps' => [
            [
                'step_number' => 1,
                'title' => [
                    'en' => 'Inquiry & Application',
                    'hi' => 'पूछताछ और आवेदन',
                    'kn' => 'ಪ್ರಶ್ನೆ ಮತ್ತು ಅರ್ಜಿ',
                ],
                'description' => [
                    'en' => 'Submit an online inquiry form or visit our campus to learn more about our programs. Complete the admission application form with all required details.',
                    'hi' => 'हमारे कार्यक्रमों के बारे में अधिक जानने के लिए ऑनलाइन पूछताछ फॉर्म जमा करें या हमारे कैंपस का दौरा करें। सभी आवश्यक विवरणों के साथ प्रवेश आवेदन फॉर्म पूरा करें।',
                    'kn' => 'ನಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳ ಬಗ್ಗೆ ಹೆಚ್ಚು ತಿಳಿಯಲು ಆನ್ಲೈನ್ ಪ್ರಶ್ನೆ ಫಾರ್ಮ್ ಸಲ್ಲಿಸಿ ಅಥವಾ ನಮ್ಮ ಕ್ಯಾಂಪಸ್ಗೆ ಭೇಟಿ ನೀಡಿ. ಎಲ್ಲಾ ಅಗತ್ಯ ವಿವರಗಳೊಂದಿಗೆ ಪ್ರವೇಶ ಅರ್ಜಿ ಫಾರ್ಮ್ ಪೂರ್ಣಗೊಳಿಸಿ.',
                ],
                'color' => 'blue',
                'icon' => 'document',
            ],
            [
                'step_number' => 2,
                'title' => [
                    'en' => 'Document Submission',
                    'hi' => 'दस्तावेज जमा करना',
                    'kn' => 'ದಾಖಲೆ ಸಲ್ಲಿಕೆ',
                ],
                'description' => [
                    'en' => 'Submit all required documents including birth certificate, previous school records, medical reports, and passport-sized photographs.',
                    'hi' => 'जन्म प्रमाण पत्र, पिछले स्कूल रिकॉर्ड, चिकित्सा रिपोर्ट और पासपोर्ट आकार की तस्वीरों सहित सभी आवश्यक दस्तावेज जमा करें।',
                    'kn' => 'ಜನನ ಪ್ರಮಾಣಪತ್ರ, ಹಿಂದಿನ ಶಾಲೆಯ ದಾಖಲೆಗಳು, ವೈದ್ಯಕೀಯ ವರದಿಗಳು ಮತ್ತು ಪಾಸ್ಪೋರ್ಟ್ ಗಾತ್ರದ ಫೋಟೋಗಳು ಸೇರಿದಂತೆ ಎಲ್ಲಾ ಅಗತ್ಯ ದಾಖಲೆಗಳನ್ನು ಸಲ್ಲಿಸಿ.',
                ],
                'color' => 'green',
                'icon' => 'folder',
            ],
            [
                'step_number' => 3,
                'title' => [
                    'en' => 'Assessment & Interview',
                    'hi' => 'मूल्यांकन और साक्षात्कार',
                    'kn' => 'ಮೌಲ್ಯಮಾಪನ ಮತ್ತು ಸಂದರ್ಶನ',
                ],
                'description' => [
                    'en' => 'Students may be required to take an assessment test. Parents and students will have an interview session with the admission committee.',
                    'hi' => 'छात्रों को मूल्यांकन परीक्षा देने की आवश्यकता हो सकती है। माता-पिता और छात्रों की प्रवेश समिति के साथ एक साक्षात्कार सत्र होगा।',
                    'kn' => 'ವಿದ್ಯಾರ್ಥಿಗಳು ಮೌಲ್ಯಮಾಪನ ಪರೀಕ್ಷೆಗೆ ಭಾಗವಹಿಸಬೇಕಾಗಬಹುದು. ಪೋಷಕರು ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಗಳು ಪ್ರವೇಶ ಸಮಿತಿಯೊಂದಿಗೆ ಸಂದರ್ಶನ ಸೆಷನ್ ಹೊಂದಿರುತ್ತಾರೆ.',
                ],
                'color' => 'purple',
                'icon' => 'clipboard',
            ],
            [
                'step_number' => 4,
                'title' => [
                    'en' => 'Admission Decision',
                    'hi' => 'प्रवेश निर्णय',
                    'kn' => 'ಪ್ರವೇಶ ನಿರ್ಧಾರ',
                ],
                'description' => [
                    'en' => 'After reviewing all applications, successful candidates will receive an admission offer letter with details about enrollment and fees.',
                    'hi' => 'सभी आवेदनों की समीक्षा के बाद, सफल उम्मीदवारों को नामांकन और शुल्क के बारे में विवरण के साथ प्रवेश प्रस्ताव पत्र प्राप्त होगा।',
                    'kn' => 'ಎಲ್ಲಾ ಅರ್ಜಿಗಳನ್ನು ಪರಿಶೀಲಿಸಿದ ನಂತರ, ಯಶಸ್ವಿ ಅಭ್ಯರ್ಥಿಗಳಿಗೆ ನೋಂದಣಿ ಮತ್ತು ಶುಲ್ಕದ ಬಗ್ಗೆ ವಿವರಗಳೊಂದಿಗೆ ಪ್ರವೇಶ ನೀಡಿಕೆ ಪತ್ರವನ್ನು ಸ್ವೀಕರಿಸುತ್ತಾರೆ.',
                ],
                'color' => 'orange',
                'icon' => 'check',
            ],
            [
                'step_number' => 5,
                'title' => [
                    'en' => 'Enrollment & Orientation',
                    'hi' => 'नामांकन और अभिविन्यास',
                    'kn' => 'ನೋಂದಣಿ ಮತ್ತು ದಿಕ್ಕು',
                ],
                'description' => [
                    'en' => 'Complete the enrollment process by paying fees and submitting final documents. Attend the orientation program to get familiar with the school.',
                    'hi' => 'शुल्क का भुगतान करके और अंतिम दस्तावेज जमा करके नामांकन प्रक्रिया पूरी करें। स्कूल से परिचित होने के लिए अभिविन्यास कार्यक्रम में भाग लें।',
                    'kn' => 'ಶುಲ್ಕವನ್ನು ಪಾವತಿಸುವ ಮೂಲಕ ಮತ್ತು ಅಂತಿಮ ದಾಖಲೆಗಳನ್ನು ಸಲ್ಲಿಸುವ ಮೂಲಕ ನೋಂದಣಿ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ. ಶಾಲೆಯೊಂದಿಗೆ ಪರಿಚಿತರಾಗಲು ದಿಕ್ಕು ಕಾರ್ಯಕ್ರಮದಲ್ಲಿ ಭಾಗವಹಿಸಿ.',
                ],
                'color' => 'teal',
                'icon' => 'users',
            ],
        ],
        'requirement_cards' => [
            [
                'title' => [
                    'en' => 'Academic Records',
                    'hi' => 'शैक्षणिक रिकॉर्ड',
                    'kn' => 'ಶೈಕ್ಷಣಿಕ ದಾಖಲೆಗಳು',
                ],
                'items' => [
                    'en' => ['Previous school transcripts', 'Report cards (last 2 years)', 'Transfer certificate'],
                    'hi' => ['पिछले स्कूल ट्रांसक्रिप्ट', 'रिपोर्ट कार्ड (पिछले 2 वर्ष)', 'स्थानांतरण प्रमाण पत्र'],
                    'kn' => ['ಹಿಂದಿನ ಶಾಲೆಯ ಪ್ರತಿಲಿಪಿಗಳು', 'ರಿಪೋರ್ಟ್ ಕಾರ್ಡ್ಗಳು (ಕೊನೆಯ 2 ವರ್ಷಗಳು)', 'ವರ್ಗಾವಣೆ ಪ್ರಮಾಣಪತ್ರ'],
                ],
                'color' => 'blue',
                'icon' => 'document',
            ],
            [
                'title' => [
                    'en' => 'Personal Documents',
                    'hi' => 'व्यक्तिगत दस्तावेज',
                    'kn' => 'ವೈಯಕ್ತಿಕ ದಾಖಲೆಗಳು',
                ],
                'items' => [
                    'en' => ['Birth certificate', 'Passport-sized photos (4 copies)', 'ID proof (Aadhaar/Passport)'],
                    'hi' => ['जन्म प्रमाण पत्र', 'पासपोर्ट आकार की तस्वीरें (4 प्रतियां)', 'आईडी प्रमाण (आधार/पासपोर्ट)'],
                    'kn' => ['ಜನನ ಪ್ರಮಾಣಪತ್ರ', 'ಪಾಸ್ಪೋರ್ಟ್ ಗಾತ್ರದ ಫೋಟೋಗಳು (4 ಪ್ರತಿಗಳು)', 'ಐಡಿ ಪುರಾವೆ (ಆಧಾರ/ಪಾಸ್ಪೋರ್ಟ್)'],
                ],
                'color' => 'green',
                'icon' => 'id',
            ],
            [
                'title' => [
                    'en' => 'Medical Records',
                    'hi' => 'चिकित्सा रिकॉर्ड',
                    'kn' => 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು',
                ],
                'items' => [
                    'en' => ['Medical fitness certificate', 'Vaccination records', 'Blood group certificate'],
                    'hi' => ['चिकित्सा फिटनेस प्रमाण पत्र', 'टीकाकरण रिकॉर्ड', 'रक्त समूह प्रमाण पत्र'],
                    'kn' => ['ವೈದ್ಯಕೀಯ ಫಿಟ್ನೆಸ್ ಪ್ರಮಾಣಪತ್ರ', 'ತಡೆಗಟ್ಟುವಿಕೆ ದಾಖಲೆಗಳು', 'ರಕ್ತ ಗುಂಪು ಪ್ರಮಾಣಪತ್ರ'],
                ],
                'color' => 'purple',
                'icon' => 'heart',
            ],
        ],
        'date_cards' => [
            [
                'label' => [
                    'en' => 'Application Opens',
                    'hi' => 'आवेदन खुलता है',
                    'kn' => 'ಅರ್ಜಿ ತೆರೆಯುತ್ತದೆ',
                ],
                'date' => [
                    'en' => 'January 1',
                    'hi' => '1 जनवरी',
                    'kn' => 'ಜನವರಿ 1',
                ],
                'description' => [
                    'en' => 'Start submitting your applications',
                    'hi' => 'अपने आवेदन जमा करना शुरू करें',
                    'kn' => 'ನಿಮ್ಮ ಅರ್ಜಿಗಳನ್ನು ಸಲ್ಲಿಸಲು ಪ್ರಾರಂಭಿಸಿ',
                ],
                'color' => 'blue',
            ],
            [
                'label' => [
                    'en' => 'Last Date',
                    'hi' => 'अंतिम तारीख',
                    'kn' => 'ಕೊನೆಯ ದಿನಾಂಕ',
                ],
                'date' => [
                    'en' => 'March 31',
                    'hi' => '31 मार्च',
                    'kn' => 'ಮಾರ್ಚ್ 31',
                ],
                'description' => [
                    'en' => 'Final deadline for applications',
                    'hi' => 'आवेदनों की अंतिम समय सीमा',
                    'kn' => 'ಅರ್ಜಿಗಳಿಗೆ ಅಂತಿಮ ಕೊನೆಯ ದಿನಾಂಕ',
                ],
                'color' => 'green',
            ],
            [
                'label' => [
                    'en' => 'Assessments',
                    'hi' => 'मूल्यांकन',
                    'kn' => 'ಮೌಲ್ಯಮಾಪನ',
                ],
                'date' => [
                    'en' => 'April 15',
                    'hi' => '15 अप्रैल',
                    'kn' => 'ಏಪ್ರಿಲ್ 15',
                ],
                'description' => [
                    'en' => 'Assessment tests scheduled',
                    'hi' => 'मूल्यांकन परीक्षाएं निर्धारित',
                    'kn' => 'ಮೌಲ್ಯಮಾಪನ ಪರೀಕ್ಷೆಗಳು ನಿಗದಿಪಡಿಸಲಾಗಿದೆ',
                ],
                'color' => 'purple',
            ],
            [
                'label' => [
                    'en' => 'Results',
                    'hi' => 'परिणाम',
                    'kn' => 'ಫಲಿತಾಂಶಗಳು',
                ],
                'date' => [
                    'en' => 'May 1',
                    'hi' => '1 मई',
                    'kn' => 'ಮೇ 1',
                ],
                'description' => [
                    'en' => 'Admission results announced',
                    'hi' => 'प्रवेश परिणाम घोषित',
                    'kn' => 'ಪ್ರವೇಶ ಫಲಿತಾಂಶಗಳು ಘೋಷಿಸಲಾಗಿದೆ',
                ],
                'color' => 'orange',
            ],
        ],
        'faq_items' => [
            [
                'question' => [
                    'en' => 'What is the age requirement for admission?',
                    'hi' => 'प्रवेश के लिए आयु आवश्यकता क्या है?',
                    'kn' => 'ಪ್ರವೇಶಕ್ಕೆ ವಯಸ್ಸಿನ ಅವಶ್ಯಕತೆ ಏನು?',
                ],
                'answer' => [
                    'en' => 'Age requirements vary by grade level. Generally, students should be age-appropriate for their grade. Please contact our admission office for specific age requirements for each grade.',
                    'hi' => 'आयु आवश्यकताएं ग्रेड स्तर के अनुसार भिन्न होती हैं। आम तौर पर, छात्र अपने ग्रेड के लिए उम्र-उपयुक्त होने चाहिए। प्रत्येक ग्रेड के लिए विशिष्ट आयु आवश्यकताओं के लिए कृपया हमारे प्रवेश कार्यालय से संपर्क करें।',
                    'kn' => 'ವಯಸ್ಸಿನ ಅವಶ್ಯಕತೆಗಳು ಗ್ರೇಡ್ ಮಟ್ಟದಿಂದ ಬದಲಾಗುತ್ತವೆ. ಸಾಮಾನ್ಯವಾಗಿ, ವಿದ್ಯಾರ್ಥಿಗಳು ತಮ್ಮ ಗ್ರೇಡ್ಗೆ ವಯಸ್ಸಿಗೆ ಸೂಕ್ತವಾಗಿರಬೇಕು. ಪ್ರತಿ ಗ್ರೇಡ್ಗೆ ನಿರ್ದಿಷ್ಟ ವಯಸ್ಸಿನ ಅವಶ್ಯಕತೆಗಳಿಗಾಗಿ ದಯವಿಟ್ಟು ನಮ್ಮ ಪ್ರವೇಶ ಕಚೇರಿಗೆ ಸಂಪರ್ಕಿಸಿ.',
                ],
            ],
            [
                'question' => [
                    'en' => 'Is there an entrance exam?',
                    'hi' => 'क्या प्रवेश परीक्षा है?',
                    'kn' => 'ಪ್ರವೇಶ ಪರೀಕ್ಷೆ ಇದೆಯೇ?',
                ],
                'answer' => [
                    'en' => 'Yes, students may be required to take an assessment test depending on the grade level. The test evaluates basic academic skills and helps us understand the student\'s learning needs.',
                    'hi' => 'हां, ग्रेड स्तर के आधार पर छात्रों को मूल्यांकन परीक्षा देने की आवश्यकता हो सकती है। परीक्षा बुनियादी शैक्षणिक कौशल का मूल्यांकन करती है और हमें छात्र की सीखने की जरूरतों को समझने में मदद करती है।',
                    'kn' => 'ಹೌದು, ಗ್ರೇಡ್ ಮಟ್ಟವನ್ನು ಅವಲಂಬಿಸಿ ವಿದ್ಯಾರ್ಥಿಗಳು ಮೌಲ್ಯಮಾಪನ ಪರೀಕ್ಷೆಗೆ ಭಾಗವಹಿಸಬೇಕಾಗಬಹುದು. ಪರೀಕ್ಷೆಯು ಮೂಲಭೂತ ಶೈಕ್ಷಣಿಕ ಕೌಶಲ್ಯಗಳನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡುತ್ತದೆ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿಯ ಕಲಿಕೆಯ ಅಗತ್ಯಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ನಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
                ],
            ],
            [
                'question' => [
                    'en' => 'What are the fee structures?',
                    'hi' => 'शुल्क संरचना क्या है?',
                    'kn' => 'ಶುಲ್ಕ ರಚನೆಗಳು ಯಾವುವು?',
                ],
                'answer' => [
                    'en' => 'Fee structures vary by grade level and program. Detailed fee information is provided during the admission process. We also offer scholarships and financial aid for eligible students.',
                    'hi' => 'शुल्क संरचना ग्रेड स्तर और कार्यक्रम के अनुसार भिन्न होती है। प्रवेश प्रक्रिया के दौरान विस्तृत शुल्क जानकारी प्रदान की जाती है। हम योग्य छात्रों के लिए छात्रवृत्ति और वित्तीय सहायता भी प्रदान करते हैं।',
                    'kn' => 'ಶುಲ್ಕ ರಚನೆಗಳು ಗ್ರೇಡ್ ಮಟ್ಟ ಮತ್ತು ಕಾರ್ಯಕ್ರಮದಿಂದ ಬದಲಾಗುತ್ತವೆ. ಪ್ರವೇಶ ಪ್ರಕ್ರಿಯೆಯ ಸಮಯದಲ್ಲಿ ವಿವರವಾದ ಶುಲ್ಕ ಮಾಹಿತಿಯನ್ನು ಒದಗಿಸಲಾಗುತ್ತದೆ. ನಾವು ಅರ್ಹ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಶಿಷ್ಯವೃತ್ತಿಗಳು ಮತ್ತು ಆರ್ಥಿಕ ಸಹಾಯವನ್ನೂ ನೀಡುತ್ತೇವೆ.',
                ],
            ],
            [
                'question' => [
                    'en' => 'Can I visit the campus before applying?',
                    'hi' => 'क्या मैं आवेदन करने से पहले कैंपस का दौरा कर सकता हूं?',
                    'kn' => 'ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮೊದಲು ನಾನು ಕ್ಯಾಂಪಸ್ಗೆ ಭೇಟಿ ನೀಡಬಹುದೇ?',
                ],
                'answer' => [
                    'en' => 'Absolutely! We encourage prospective families to visit our campus. You can schedule a campus tour by contacting our admission office. We also organize open house events throughout the year.',
                    'hi' => 'बिल्कुल! हम संभावित परिवारों को हमारे कैंपस का दौरा करने के लिए प्रोत्साहित करते हैं। आप हमारे प्रवेश कार्यालय से संपर्क करके कैंपस दौरे की योजना बना सकते हैं। हम पूरे वर्ष खुले घर कार्यक्रम भी आयोजित करते हैं।',
                    'kn' => 'ಸಂಪೂರ್ಣವಾಗಿ! ನಾವು ಸಂಭಾವ್ಯ ಕುಟುಂಬಗಳನ್ನು ನಮ್ಮ ಕ್ಯಾಂಪಸ್ಗೆ ಭೇಟಿ ನೀಡಲು ಪ್ರೋತ್ಸಾಹಿಸುತ್ತೇವೆ. ನಮ್ಮ ಪ್ರವೇಶ ಕಚೇರಿಗೆ ಸಂಪರ್ಕಿಸುವ ಮೂಲಕ ನೀವು ಕ್ಯಾಂಪಸ್ ಪ್ರವಾಸವನ್ನು ನಿಗದಿಪಡಿಸಬಹುದು. ನಾವು ವರ್ಷದುದ್ದಕ್ಕೂ ಮುಕ್ತ ಮನೆ ಕಾರ್ಯಕ್ರಮಗಳನ್ನೂ ಸಂಘಟಿಸುತ್ತೇವೆ.',
                ],
            ],
        ],
    ],
];
