<?php

namespace App\Helpers;

class ComponentHelper
{
    /**
     * Get Tailwind color classes for a color name
     */
    public static function getColorClasses(string $color): array
    {
        $colorMap = [
            'primary' => [
                'bg' => 'bg-primary-600',
                'bg_light' => 'bg-primary-100',
                'bg_light_2' => 'bg-primary-200',
                'bg_gradient_from' => 'from-primary-50',
                'bg_gradient_via' => 'via-primary-100',
                'bg_gradient_to' => 'to-primary-50',
                'text' => 'text-primary-600',
                'text_light' => 'text-primary-100',
                'border' => 'border-primary-200',
                'hover_bg' => 'hover:bg-primary-700',
            ],
            'green' => [
                'bg' => 'bg-green-600',
                'bg_light' => 'bg-green-100',
                'bg_light_2' => 'bg-green-200',
                'bg_gradient_from' => 'from-green-50',
                'bg_gradient_via' => 'via-green-100',
                'bg_gradient_to' => 'to-green-50',
                'text' => 'text-green-600',
                'text_light' => 'text-green-100',
                'border' => 'border-green-200',
                'hover_bg' => 'hover:bg-green-700',
            ],
            'blue' => [
                'bg' => 'bg-blue-600',
                'bg_light' => 'bg-blue-100',
                'bg_light_2' => 'bg-blue-200',
                'bg_gradient_from' => 'from-blue-50',
                'bg_gradient_via' => 'via-blue-100',
                'bg_gradient_to' => 'to-blue-50',
                'text' => 'text-blue-600',
                'text_light' => 'text-blue-100',
                'border' => 'border-blue-200',
                'hover_bg' => 'hover:bg-blue-700',
            ],
            'purple' => [
                'bg' => 'bg-purple-600',
                'bg_light' => 'bg-purple-100',
                'bg_light_2' => 'bg-purple-200',
                'bg_gradient_from' => 'from-purple-50',
                'bg_gradient_via' => 'via-purple-100',
                'bg_gradient_to' => 'to-purple-50',
                'text' => 'text-purple-600',
                'text_light' => 'text-purple-100',
                'border' => 'border-purple-200',
                'hover_bg' => 'hover:bg-purple-700',
            ],
            'red' => [
                'bg' => 'bg-red-600',
                'bg_light' => 'bg-red-100',
                'bg_light_2' => 'bg-red-200',
                'bg_gradient_from' => 'from-red-50',
                'bg_gradient_via' => 'via-red-100',
                'bg_gradient_to' => 'to-red-50',
                'text' => 'text-red-600',
                'text_light' => 'text-red-100',
                'border' => 'border-red-200',
                'hover_bg' => 'hover:bg-red-700',
            ],
            'yellow' => [
                'bg' => 'bg-yellow-600',
                'bg_light' => 'bg-yellow-100',
                'bg_light_2' => 'bg-yellow-200',
                'bg_gradient_from' => 'from-yellow-50',
                'bg_gradient_via' => 'via-yellow-100',
                'bg_gradient_to' => 'to-yellow-50',
                'text' => 'text-yellow-600',
                'text_light' => 'text-yellow-100',
                'border' => 'border-yellow-200',
                'hover_bg' => 'hover:bg-yellow-700',
            ],
            'orange' => [
                'bg' => 'bg-orange-600',
                'bg_light' => 'bg-orange-100',
                'bg_light_2' => 'bg-orange-200',
                'bg_gradient_from' => 'from-orange-50',
                'bg_gradient_via' => 'via-orange-100',
                'bg_gradient_to' => 'to-orange-50',
                'text' => 'text-orange-600',
                'text_light' => 'text-orange-100',
                'border' => 'border-orange-200',
                'hover_bg' => 'hover:bg-orange-700',
            ],
            'indigo' => [
                'bg' => 'bg-indigo-600',
                'bg_light' => 'bg-indigo-100',
                'bg_light_2' => 'bg-indigo-200',
                'bg_gradient_from' => 'from-indigo-50',
                'bg_gradient_via' => 'via-indigo-100',
                'bg_gradient_to' => 'to-indigo-50',
                'text' => 'text-indigo-600',
                'text_light' => 'text-indigo-100',
                'border' => 'border-indigo-200',
                'hover_bg' => 'hover:bg-indigo-700',
            ],
            'pink' => [
                'bg' => 'bg-pink-600',
                'bg_light' => 'bg-pink-100',
                'bg_light_2' => 'bg-pink-200',
                'bg_gradient_from' => 'from-pink-50',
                'bg_gradient_via' => 'via-pink-100',
                'bg_gradient_to' => 'to-pink-50',
                'text' => 'text-pink-600',
                'text_light' => 'text-pink-100',
                'border' => 'border-pink-200',
                'hover_bg' => 'hover:bg-pink-700',
            ],
            'teal' => [
                'bg' => 'bg-teal-600',
                'bg_light' => 'bg-teal-100',
                'bg_light_2' => 'bg-teal-200',
                'bg_gradient_from' => 'from-teal-50',
                'bg_gradient_via' => 'via-teal-100',
                'bg_gradient_to' => 'to-teal-50',
                'text' => 'text-teal-600',
                'text_light' => 'text-teal-100',
                'border' => 'border-teal-200',
                'hover_bg' => 'hover:bg-teal-700',
            ],
            'cyan' => [
                'bg' => 'bg-cyan-600',
                'bg_light' => 'bg-cyan-100',
                'bg_light_2' => 'bg-cyan-200',
                'bg_gradient_from' => 'from-cyan-50',
                'bg_gradient_via' => 'via-cyan-100',
                'bg_gradient_to' => 'to-cyan-50',
                'text' => 'text-cyan-600',
                'text_light' => 'text-cyan-100',
                'border' => 'border-cyan-200',
                'hover_bg' => 'hover:bg-cyan-700',
            ],
        ];

        return $colorMap[$color] ?? $colorMap['primary'];
    }
}
