name: school-erp
domain: myschool.test
subdomains:
  - app  # Internal Admin
  - dps  # Delhi Public School
  - misa  # Mumbai International School
  - bta  # Bangalore Tech Academy
php: 8.3
mysql: 8.0
redis: 7.0  # Updated again
